#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################

name: $(DayOfYear)$(Rev:rr)

#parameters:

variables:
  - template: /eng/pipelines/common/variables/common-variables.yml@self

stages:
  # Stage 1: Build and pack all projects in the repository
  - template: /eng/pipelines/prci/stages/build-and-pack-stage.yml
    parameters:
      buildConfiguration: Debug
      buildSuffix: pr
