####################################################################################################
# Licensed to the .NET Foundation under one or more agreements.  The .NET Foundation licenses this
# file to you under the MIT license.  See the LICENSE file in the project root for more information.
####################################################################################################

# This stage generates the following random secrets for use throughout the PR and CI pipelines:
#
#   SaPassword  -  A random GUID suitable for use as the SA password of local SQL Server instances.
#
# Subsequent stages may reference these variables as:
#
#   $[stageDependencies.secrets_stage.secrets_job.outputs['SaPassword.Value']]
#
# For further details on the stage-dependency syntax, see:
#
#   https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-variables-scripts?view=azure-devops&tabs=bash#set-an-output-variable-for-use-in-future-stages
#
# Any stages that use these secrets must depend on this stage:
#
#   secrets_stage
#
# None of the values produced here are actual secrets - they are just random values that are
# suitable for testing purposes, and do not need to be protected.  For simplicity, they are emitted
# as regular output variables of script steps, are not formally marked as secrets, and not stored in
# the Azure DevOps Library or Key Vault.
#
parameters:

  # True to emit debugging steps and messages.
  - name: debug
    type: boolean
    default: false

stages:

  # The stage downstream stages must depend on to ensure the secrets are generated before they are
  # used.
  - stage: secrets_stage
    displayName: Generate Secrets
    jobs:

      # The job that generates the secrets.  Each secret is emitted as an output variable of a
      # script step, and can be referenced by downstream stages via the stage-dependencies syntax.
      - job: secrets_job
        displayName: Generate Secrets
        pool:
          # We don't need anything special, so use the standard Microsoft-hosted Ubuntu image, which
          # is typically very fast to spin up.
          vmImage: ubuntu-latest

        steps:

          # We don't need the repo checked out.
          - checkout: none

          # Generate a password suitable for the SA user of local SQL Server instances.
          #
          # This creates the SaPassword.Value variable.
          #
          - bash: |
              guid=$(cat /proc/sys/kernel/random/uuid)
              echo "##vso[task.setvariable variable=Value;isOutput=true]$guid"
            name: SaPassword
            displayName: Generate SA password

          # Emit the SA password, if desired.
          - ${{ if eq(parameters.debug, true) }}:
            - bash: |
                echo "SA password: $(SaPassword.Value)"
              displayName: '[Debug] Emit SA password'
