####################################################################################################
# Licensed to the .NET Foundation under one or more agreements.  The .NET Foundation licenses this
# file to you under the MIT license.  See the LICENSE file in the project root for more information.
####################################################################################################

# This stage generates the following random secrets for use throughout the PR and CI pipelines:
#
#   SaPassword  -  A random GUID suitable for use as the SA password of local SQL Server instances.
#
# Subsequent stages may reference these variables as:
#
#   $[stageDependencies.secrets_stage.secrets_job.outputs['SaPassword.Value']]
#
# For further details on the stage-dependency syntax, see:
#
#   https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-variables-scripts?view=azure-devops&tabs=bash#set-an-output-variable-for-use-in-future-stages
#
# Any stages that use these secrets must depend on this stage:
#
#   secrets_stage

stages:
  - stage: secrets_stage
    displayName: Generate Secrets
    jobs:
      - job: secrets_job
        displayName: Generate Secrets
        pool:
          vmImage: ubuntu-latest
        steps:

          # Generate a password suitable for the SA user of local SQL Server instances.
          #
          # This creates the SaPassword.Value variable.
          #
          - bash: |
              guid=$(cat /proc/sys/kernel/random/uuid)
              echo "##vso[task.setvariable variable=Value;isSecret=true;isOutput=true]$guid"
            name: SaPassword
            displayName: Generate SA password
