#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################
parameters:

  # The assembly file version to apply to the Abstractions package.
  - name: abstractionsAssemblyFileVersion
    type: string

  # The version to apply to the Abstractions package.
  - name: abstractionsPackageVersion
    type: string

  # The assembly file version to apply to the Logging package.
  - name: loggingAssemblyFileVersion
    type: string

  # The version to apply to the Logging package.
  - name: loggingPackageVersion
    type: string

  # The assembly file version to apply to the Mds package.
  - name: mdsAssemblyFileVersion
    type: string

  # The version to apply to the Mds package.
  - name: mdsPackageVersion
    type: string

steps:
  # Download our signing key.
  - task: DownloadSecureFile@1
    displayName: 'Download Key Pair'
    inputs:
      secureFile: netfxKeypair.snk
    name: keyFile

  # Install the .NET SDK.
  - template: /eng/pipelines/steps/install-dotnet.yml@self

  - task: MSBuild@1
    displayName: 'BuildMds using build2.proj'
    inputs:
      solution: '**/build2.proj'
      configuration: Release
      msbuildArguments: >-
        -t:BuildMds
        -p:ReferenceType=Package
        -p:SigningKeyPath="$(keyFile.secureFilePath)"
        -p:PackageVersionMds=${{ parameters.mdsPackageVersion }}
        -p:PackageVersionAbstractions=${{ parameters.abstractionsPackageVersion }}
        -p:PackageVersionLogging=${{ parameters.loggingPackageVersion }}
