#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################
parameters:
  - name: password
    type: string
    default: $(password)

  - name: condition
    type: string
    default: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))

steps:
# Linux only steps
- bash: |
    # The "user" pipeline variable conflicts with homebrew, causing errors during install. Set it back to the pipeline user.
    USER=`whoami`

    brew install colima
    brew install --cask docker
    brew tap microsoft/mssql-release https://github.com/Microsoft/homebrew-mssql-release
    brew update
    HOMEBREW_ACCEPT_EULA=Y brew install mssql-tools18
    colima start
    docker --version
    docker pull mcr.microsoft.com/mssql/server:2022-latest
    
    # Password for the SA user (required)
    MSSQL_SA_PW=${{parameters.password }}
    if [ "$MSSQL_SA_PW" = "generated_placeholder" ]; then
      exit 0
    fi
 
    docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=$MSSQL_SA_PW" -p 1433:1433 --name sql1 --hostname sql1 -d mcr.microsoft.com/mssql/server:2022-latest
    #docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=$MSSQL_SA_PW" --network=host --name sql1 --hostname sql1 -d mcr.microsoft.com/mssql/server:2022-latest

    sleep 5

    docker ps -a

    docker exec sql1 /opt/mssql-tools18/bin/sqlcmd \
    -S localhost -No -U SA -P $MSSQL_SA_PW \
    -Q "SELECT @@VERSION"

    ping -c 4 localhost

    cat /etc/hosts

    echo 0.0.0.0
    sqlcmd -S 0.0.0.0 -No -U sa -P $MSSQL_SA_PW -Q "SELECT @@VERSION"
    echo ::
    sqlcmd -S :: -No -U sa -P $MSSQL_SA_PW -Q "SELECT @@VERSION"
    echo localhost
    sqlcmd -S localhost -No -U sa -P $MSSQL_SA_PW -Q "SELECT @@VERSION"
    echo "(default)"
    sqlcmd -No -U sa -P $MSSQL_SA_PW -Q "SELECT @@VERSION"

    echo "0.0.0.0 localhost" >> /etc/hosts
    cat /etc/hosts

    echo 0.0.0.0
    sqlcmd -S 0.0.0.0 -No -U sa -P $MSSQL_SA_PW -Q "SELECT @@VERSION"
    echo ::
    sqlcmd -S :: -No -U sa -P $MSSQL_SA_PW -Q "SELECT @@VERSION"
    echo localhost
    sqlcmd -S localhost -No -U sa -P $MSSQL_SA_PW -Q "SELECT @@VERSION"
    echo "(default)"
    sqlcmd -No -U sa -P $MSSQL_SA_PW -Q "SELECT @@VERSION"

    docker ps -a
    docker exec -t sql1 cat /var/opt/mssql/log/errorlog | grep connection
    docker logs sql1

    # Connect to server and get the version:
    counter=1
    errstatus=1
    while [ $counter -le 5 ] && [ $errstatus = 1 ]
    do
      echo Waiting for SQL Server to start...
      sleep 3
      sqlcmd \
        -S localhost \
        -No \
        -U sa \
        -P $MSSQL_SA_PW\
        -Q "SELECT @@VERSION" # 2>/dev/null
      errstatus=$?
      ((counter++))
    done

    docker exec sql1 /opt/mssql-tools18/bin/sqlcmd \
    -S localhost -No -U SA -P $MSSQL_SA_PW \
    -Q "SELECT @@VERSION"

    # Display error if connection failed:
    if [ $errstatus = 1 ]
    then
      echo Cannot connect to SQL Server, installation aborted
      exit $errstatus
    else
      sqlcmd \
        -S localhost \
        -No \
        -U sa \
        -P $MSSQL_SA_PW\
        -Q "SELECT @@VERSION"
    fi
  displayName: 'Configure SQL Server [macOS]'
  condition: ${{parameters.condition }}
