################################################################################
# Licensed to the .NET Foundation under one or more agreements.                #
# The .NET Foundation licenses this file to you under the MIT license.         #
# See the LICENSE file in the project root for more information.               #
################################################################################

# This job performs Roslyn analysis on the Abstractions project.

parameters:

  # The build configuration to use.
  - name: buildConfiguration
    type: string
    values:
      - Debug
      - Release

  # True to enable debug steps and logging.
  - name: debug
    type: boolean
    default: false

  # The verbosity level for the dotnet CLI commands.
  - name: dotnetVerbosity
    type: string
    default: normal
    values:
    - quiet
    - minimal
    - normal
    - detailed
    - diagnostic

  # The value we will set as the ob_outputDirectory variable, required by the OneBranch templates.
  # level.
  - name: onebranchOutputDirectory
    type: string

jobs:
  - job: abstractions_analysis_job
    displayName: Analysis

    pool:
      # The Roslyn analyzers require a Windows agent with Visual Studio.
      type: windows

    variables:
      # The OneBranch templates require that the $(ob_outputDirectory) variable be defined at every
      # job level.
      - name: ob_outputDirectory
        value: ${{ parameters.onebranchOutputDirectory }}

    steps:
      # Install the .NET SDK.
      - template: /eng/pipelines/steps/install-dotnet.yml@self

      # Build the Abstractions project.  Roslyn analysis requires the project to have been built
      # before analysis can take place.
      - task: DotNetCoreCLI@2
        displayName: Build Project
        inputs:
          command: custom
          custom: build
          projects: $(projectPath)
          arguments: >-
            --artifacts-path $(artifactsPath)
            --configuration ${{ parameters.buildConfiguration }}
            --verbosity ${{ parameters.dotnetVerbosity }}

      # Perform the analysis with the 1ES Roslyn Analyzer:
      #
      # https://eng.ms/docs/coreai/devdiv/one-engineering-system-1es/1es-mohanb/security-integration/guardian-wiki/sdl-azdo-extension/roslyn-analyzers-build-task
      - task: securedevelopmentteam.vss-secure-development-tools.build-task-roslynanalyzers.RoslynAnalyzers@3
        displayName: Roslyn Analysis
        inputs:
          userProvideBuildInfo: autoMsBuildInfo
          rulesetName: Recommended
          rulesetVersion: Latest
          policyName: Microsoft
          loadRoslynConfiguredAnalyzersOption: Enable
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)

      # Symlink the assemblies (DLLs and PDBs) to a dedicated folder for ApiScan.
      - script: |
          # Lower-case the build configuration for use in paths.
          BUILD_CONFIG="${{ parameters.buildConfiguration }}"
          BUILD_CONFIG=${BUILD_CONFIG,,}

          # Create the symlink from artifacts -> assemblies.
          ln -s $(artifactsPath)/bin/Abstractions/${BUILD_CONFIG}_netstandard2.0 $(apiScanPath)
        displayName: Symlink Assemblies for ApiScan
