################################################################################
# Licensed to the .NET Foundation under one or more agreements.                #
# The .NET Foundation licenses this file to you under the MIT license.         #
# See the LICENSE file in the project root for more information.               #
################################################################################

# This job performs Roslyn analysis on the Abstractions project.

parameters:

  # The build configuration to use.
  - name: buildConfiguration
    type: string
    values:
      - Debug
      - Release

  # True to enable debug steps and logging.
  - name: debug
    type: boolean
    default: false

  # The verbosity level for the dotnet CLI commands.
  - name: dotnetVerbosity
    type: string
    default: normal
    values:
    - quiet
    - minimal
    - normal
    - detailed
    - diagnostic

jobs:
  - job: abstractions_analysis_job
    displayName: Analysis

    pool:
      # The Roslyn analyzers require a Windows agent with Visual Studio.
      type: windows

    # variables:
      # OneBranch requires that each job explicitly define the ob_outputDirectory - it cannot be
      # inherited from previous jobs or stages.
      #
      # Our variables.yml defines several paths where interesting artifacts are placed, all of
      # which are sub-directories of this one.  All jobs set ob_outputDirectory identically.
      #
      # - name: ob_outputDirectory
      #   value: $(Agent.BuildDirectory)/build

    steps:
      # Install the .NET SDK.
      - template: /eng/pipelines/steps/install-dotnet.yml@self

      # Build the Abstractions project.  Roslyn analysis requires the project to have been built
      # before analysis can take place.
      - task: DotNetCoreCLI@2
        displayName: Build Project
        inputs:
          command: custom
          custom: build
          projects: $(projectPath)
          arguments: >-
            --configuration ${{ parameters.buildConfiguration }}
            -p:AbstractionsAssemblyFileVersion=$(assemblyFileVersion)
            -p:AbstractionsPackageVersion=$(packageVersion)
            -p:ReferenceType=Package
            --verbosity ${{ parameters.dotnetVerbosity }}

      # Perform the analysis with the 1ES Roslyn Analyzer:
      #
      # https://eng.ms/docs/coreai/devdiv/one-engineering-system-1es/1es-mohanb/security-integration/guardian-wiki/sdl-azdo-extension/roslyn-analyzers-build-task
      - task: securedevelopmentteam.vss-secure-development-tools.build-task-roslynanalyzers.RoslynAnalyzers@3
        displayName: Roslyn Analysis
        inputs:
          userProvideBuildInfo: autoMsBuildInfo
          rulesetName: Recommended
          rulesetVersion: Latest
          policyName: Microsoft
          loadRoslynConfiguredAnalyzersOption: Enable
