################################################################################
# Licensed to the .NET Foundation under one or more agreements.                #
# The .NET Foundation licenses this file to you under the MIT license.         #
# See the LICENSE file in the project root for more information.               #
################################################################################

# This is the official build and release pipeline for the Abstractions package.

name: $(Year:YY)$(DayOfYear)$(Rev:.r)

# Never run due to PRs.
pr: none

# Run on pushes to the ADO.Net dotnet-sqlclient internal/main branch.
trigger:
  branches:
    include:
      - internal/main

# Run weekly on Sundays at 13:00 UTC
schedules:
  - cron: '0 13 * * 0' # Weekly on Sunday at 13:00 UTC
    displayName: Weekly Run
    branches:
      include:
        - internal/main
    always: true

# Parameters visible in the Azure DevOps UI.
parameters:

  # We build in Release mode by default.
  - name: buildConfiguration
    displayName: Build configuration
    type: string
    values:
      - Debug
      - Release
    default: Release

  # True to enable debug steps and logging.
  - name: debug
    displayName: Enable debug steps and logging
    type: boolean
    default: false

  # The verbosity level for the dotnet CLI commands.
  - name: dotnetVerbosity
    type: string
    default: normal
    values:
    - quiet
    - minimal
    - normal
    - detailed
    - diagnostic

  # True to publish symbols after a successful build.
  # We don't publish symbols by default.  This is to avoid cluttering the symbol
  # servers with symbols from automated runs.
  - name: publishSymbols
    displayName: Publish symbols
    type: boolean
    default: false

variables:
   # Needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)]

  # Docker image which is used to build the project https://aka.ms/obpipelines/containers
  LinuxContainerImage: mcr.microsoft.com/onebranch/azurelinux/build:3.0

  DEBIAN_FRONTEND: noninteractive

# We extend the latest version of the OneBranch official pipeline template.
# These are injected into the SqlClientDrivers organization as the
# OneBranch.Pipelines project, in the GovernedTemplates repository.
resources:
  repositories:
    - repository: templates
      type: 'git'
      name: 'OneBranch.Pipelines/GovernedTemplates'
      ref: 'refs/heads/main'

# Extend the Official pipeline, inspired by:
#
# https://sqlclientdrivers.visualstudio.com/OneBranch.Pipelines/_git/GovernedTemplates?path=/UserPipelines/Linux/OneBranch.Official.CrossPlat.yml
extends:
  template: /v2/OneBranch.Official.CrossPlat.yml@templates

  parameters:

    # See https://aka.ms/obpipelines/sdl
    globalSdl:

      apiscan:
        enabled: ${{ parameters.runSdlTasks }}
        softwareFolder: '${{ variables.apiScanDllPath }}'
        softwareName: 'Microsoft.Data.SqlClient' # Note: This name is registered with ApiScan
        softwareVersionNum: '${{ variables.assemblyFileVersion }}'
        symbolsFolder: '${{ variables.apiScanPdbPath }}'

      armory:
        enabled: ${{ parameters.runSdlTasks }}
        break: true

      asyncSdl:
        # If this should be enabled, move supported tools under this item,
        # see https://aka.ms/obpipelines/asyncsdl
        enabled: false

      binskim:
        enabled: ${{ parameters.runSdlTasks }}
        break: true

      codeinspector:
        enabled: ${{ parameters.runSdlTasks }}
        logLevel: Error

      codeql:
        enabled: ${{ parameters.runSdlTasks }}
        sourceRoot: '$(REPO_ROOT)/src/Microsoft.Data.SqlClient/add-ons/AzureKeyVaultProvider'
        # Note, this can only be done if project doesn't depend on other projects. In
        #    package reference mode, this is true, but if we ever enable project reference
        #    builds, this will have to be removed.

      credscan:
        enabled: ${{ parameters.runSdlTasks }}
        suppressionsFile: '$(REPO_ROOT)/.config/CredScanSuppressions.json'

      eslint:
        enabled: false

      policheck:
        enabled: ${{ parameters.runSdlTasks }}
        break: true
        exclusionFile: '$(REPO_ROOT)/.config/PolicheckExclusions.xml'

      roslyn:
        enabled: ${{ parameters.runSdlTasks }}
        break: true
        # Requires RoslynAnalyzers task to be added somewhere in
        # the build stage.

      publishLogs:
        enabled: ${{ parameters.runSdlTasks }}

      sbom:
        enabled: ${{ parameters.runSdlTasks }}
        packageName: 'Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider'
        packageVersion: ${{ variables.akvPackageVersion }}

      tsa:
        # OneBranch publishes all sdl results to TSA. If TSA is disabled all SDL tools will
        # be forced into 'break' build mode.
        enabled: ${{ eq(parameters.oneBranchType, 'Official') }}
        configFile: '$(REPO_ROOT)/.config/tsaoptions.json'

    stages:
      - stage:  build_abstractions
        displayName: Build Abstractions
        jobs:
          - template: /eng/pipelines/abstractions/official/build-job.yml@self
            parameters:
              abstractionsPackageVersion: ${{ variables.mdsPackageVersion }}
              buildConfiguration: ${{ parameters.buildConfiguration }}
              debug: ${{ parameters.debug }}

              apiScanDllPath: '${{ variables.apiScanDllPath }}'
              apiScanPdbPath: '${{ variables.apiScanPdbPath }}'
              buildConfiguration: '${{ parameters.buildConfiguration }}'
              mdsPackageVersion: '${{ variables.mdsPackageVersion }}'
              publishSymbols: '${{ parameters.publishSymbols }}'
              signingAppRegistrationClientId: '$(SigningAppRegistrationClientId)'
              signingAppRegistrationTenantId: '$(SigningAppRegistrationTenantId)'
              signingAuthAkvName: '$(SigningAuthAkvName)'
              signingAuthSignCertName: '$(SigningAuthSignCertName)'
              signingEsrpClientId: '$(SigningEsrpClientId)'
              signingEsrpConnectedServiceName: '$(SigningEsrpConnectedServiceName)'
              symbolsAzureSubscription: '$(SymbolsAzureSubscription)'
              symbolsPublishProjectName: '$(SymbolsPublishProjectName)'
              symbolsPublishServer: '$(SymbolsPublishServer)'
              symbolsPublishTokenUri: '$(SymbolsPublishTokenUri)'
              symbolsUploadAccount: '$(SymbolsUploadAccount)'

      - stage: test_abstractions
        displayName: Test Abstractions
        jobs:
          - template: /eng/pipelines/abstractions/official/test-job.yml@self

      - stage: release_abstrations
        displayName: Release Abstractions
        dependsOn: [build_abstractions, test_abstractions]
        jobs:
          - template: /eng/pipelines/abstractions/official/release-job.yml@self
