################################################################################
# Licensed to the .NET Foundation under one or more agreements.                #
# The .NET Foundation licenses this file to you under the MIT license.         #
# See the LICENSE file in the project root for more information.               #
################################################################################

# This job runs unit tests for the Abstractions project.

parameters:

  # The build configuration to use.
  - name: buildConfiguration
    type: string
    values:
      - Debug
      - Release

  # True to enable debug steps and logging.
  - name: debug
    type: boolean
    default: false

  # The verbosity level for the dotnet CLI commands.
  - name: dotnetVerbosity
    type: string
    default: normal
    values:
    - quiet
    - minimal
    - normal
    - detailed
    - diagnostic

  # The value we will set as the ob_outputDirectory variable, required by the OneBranch templates.
  # level.
  - name: onebranchOutputDirectory
    type: string

jobs:
  - job: abstractions_test_job
    displayName: Run Unit Tests

    pool:
      type: linux

    variables:
      # The OneBranch templates require that the $(ob_outputDirectory) variable be defined at every
      # job level.
      - name: ob_outputDirectory
        value: ${{ parameters.onebranchOutputDirectory }}

    steps:
      # Install the .NET SDK.
      - template: /eng/pipelines/steps/install-dotnet.yml@self

      # Run the unit tests.
      - task: DotNetCoreCLI@2
        displayName: Run Unit Tests
        inputs:
          command: custom
          custom: test
          projects: $(testProjectPath)
          arguments: >-
            --configuration ${{ parameters.buildConfiguration }}
            --verbosity ${{ parameters.dotnetVerbosity }}
