####################################################################################################
# Licensed to the .NET Foundation under one or more agreements.  The .NET Foundation licenses this
# file to you under the MIT license.  See the LICENSE file in the project root for more information.
####################################################################################################

# This stage builds and runs stress tests against the SqlClient projects, building them transitively
# as necessary.
#
# The stress tests are located here:
#
#   src/Microsoft.Data.SqlClient/tests/StressTests
#
# All tests use a localhost SQL Server configured for SQL auth via the 'sa' user and the generated
# password.
#
# This stage depends on the secrets_stage.
#
# This template defines a stage named 'stress_tests_stage' that can be depended on by downstream
# stages.

parameters:

  # The type of build to produce (Debug or Release)
  - name: buildConfiguration
    type: string
    values:
      - Debug
      - Release

  # True to enable debugging steps.
  - name: debug
    type: boolean
    default: false

  # The verbosity level for the dotnet CLI commands.
  - name: dotnetVerbosity
    type: string
    default: normal
    values:
    - quiet
    - minimal
    - normal
    - detailed
    - diagnostic

  # The list of .NET Framework runtimes to test against.
  - name: netFrameworkTestRuntimes
    type: object
    default: [net462]

  # The list of .NET runtimes to test against.
  - name: netTestRuntimes
    type: object
    default: [net8.0, net9.0, net10.0]

stages:
  - stage: stress_tests_stage
    displayName: Run Stress Tests
    dependsOn:
      - secrets_stage

    variables:
      # Bring the SA password from the secrets_stage into scope here.
      - name: saPassword
        value: $[stageDependencies.secrets_stage.secrets_job.outputs['SaPassword.Value']]

    jobs:

    # ----------------------------------------------------------------------------------------------
    # Build and test on Linux.

    - template: /eng/pipelines/stress/stress-tests-job.yml@self
      parameters:
        buildConfiguration: ${{ parameters.buildConfiguration }}
        debug: ${{ parameters.debug }}
        displayNamePrefix: Linux
        dotnetVerbosity: ${{ parameters.dotnetVerbosity }}
        jobNameSuffix: linux
        netTestRuntimes: ${{ parameters.netTestRuntimes }}
        poolName: ADO-CI-1ES-Pool
        saPassword: $(saPassword)
        sqlSetupStep:
          template: /eng/pipelines/common/templates/steps/configure-sql-server-linux-step.yml@self
          parameters:
            saPassword: $(saPassword)
        vmImage: ADO-UB22-SQL22

    # ----------------------------------------------------------------------------------------------
    # Build and test on Windows

    - template: /eng/pipelines/stress/stress-tests-job.yml@self
      parameters:
        buildConfiguration: ${{ parameters.buildConfiguration }}
        debug: ${{ parameters.debug }}
        displayNamePrefix: Win
        dotnetVerbosity: ${{ parameters.dotnetVerbosity }}
        jobNameSuffix: windows
        # Note that we include the .NET Framework runtimes for test runs on Windows.
        netFrameworkTestRuntimes: ${{ parameters.netFrameworkTestRuntimes }}
        netTestRuntimes: ${{ parameters.netTestRuntimes }}
        poolName: ADO-CI-1ES-Pool
        saPassword: $(saPassword)
        sqlSetupStep:
          template: /eng/pipelines/common/templates/steps/configure-sql-server-win-step.yml@self
          parameters:
            saPassword: $(saPassword)
        # The Windows images include a suitable .NET Framework runtime, so we don't have to install
        # one explicitly.
        vmImage: ADO-MMS22-SQL22

    # ----------------------------------------------------------------------------------------------
    # Build and test on macOS.

    - template: /eng/pipelines/stress/stress-tests-job.yml@self
      parameters:
        buildConfiguration: ${{ parameters.buildConfiguration }}
        debug: ${{ parameters.debug }}
        displayNamePrefix: macOS
        dotnetVerbosity: ${{ parameters.dotnetVerbosity }}
        jobNameSuffix: macos
        netTestRuntimes: ${{ parameters.netTestRuntimes }}
        # We don't have any 1ES Hosted Pool images for macOS, so we use a generic one from Azure
        # Pipelines.
        poolName: Azure Pipelines
        saPassword: $(saPassword)
        sqlSetupStep:
          template: /eng/pipelines/common/templates/steps/configure-sql-server-macos-step.yml@self
          parameters:
            saPassword: $(saPassword)
        vmImage: macos-latest
