<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
    <ILLinkTreatWarningsAsErrors>true</ILLinkTreatWarningsAsErrors>
    <IlcTreatWarningsAsErrors>true</IlcTreatWarningsAsErrors>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <PublishTrimmed Condition="'$(PublishMode)' == 'trim'">true</PublishTrimmed>
    <PublishAot Condition="'$(PublishMode)' == 'aot'">true</PublishAot>
  </PropertyGroup>
  <ItemGroup Condition="'$(ReferenceType)' == 'Project'">
    <ProjectReference Include="$(RepoRoot)src/Microsoft.Data.SqlClient.Extensions/Abstractions/src/Abstractions.csproj"
                      GlobalPropertiesToRemove="PublishTrimmed;PublishAot" />
    <ProjectReference Include="$(RepoRoot)src/Microsoft.Data.SqlClient.Extensions/Azure/src/Azure.csproj"
                      GlobalPropertiesToRemove="PublishTrimmed;PublishAot" />
  </ItemGroup>
  <ItemGroup Condition="'$(ReferenceType)' == 'Package'">
    <PackageReference Include="Microsoft.Data.SqlClient.Extensions.Abstractions" />
    <PackageReference Include="Microsoft.Data.SqlClient.Extensions.Azure" />
  </ItemGroup>
</Project>
