#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################

name: $(DayOfYear)$(Rev:rr)

parameters:
  # Name of the pool to use for jobs that require customized VM images.
  - name: poolName
    type: string
    default: $(PoolNameDefault)

variables:
  - template: /eng/pipelines/common/variables/common-variables.yml@self
  - template: /eng/pipelines/pr/variables/pr-variables.yml@self

stages:
  # Stage 1a: Build and pack all projects in the repository
  - template: /eng/pipelines/pr/stages/pack-stage.yml
    parameters:
      buildConfiguration: Debug
      buildSuffix: pr
      stageName: ${{ variables.stageNamePack }}

  # Stage 1b: Generate secrets
  - template: /eng/pipelines/pr/stages/generate-secrets-stage.yml
    parameters:
      stageName: ${{ variables.stageNameSecrets }}

  # Stage 2: Execute tests and collect code coverage
  - template: /eng/pipelines/pr/stages/test-stages.yml
    parameters:
      buildConfiguration: Debug
      buildSuffix: pr
      poolName: ${{ parameters.poolName }}
      stageNamePack: ${{ variables.stageNamePack }}
      stageNameSecrets: ${{ variables.stageNameSecrets }}

      platforms:
        - displayName: "windows_net462"
          dotnet: "net462"
          image: "ADO-MMS22-SQL22"
          operatingSystem: "Windows"
        - displayName: "windows_net8"
          dotnet: "net8.0"
          image: "ADO-MMS22-SQL22"
          operatingSystem: "Windows"
        - displayName: "windows_net9"
          dotnet: "net9.0"
          image: "ADO-MMS22-SQL22"
          operatingSystem: "Windows"
        - displayName: "windows_net10"
          dotnet: "net10.0"
          image: "ADO-MMS22-SQL22"
          operatingSystem: "Windows"

        - displayName: "linux_net8"
          dotnet: "net8.0"
          image: "ADO-UB22-SQL22"
          operatingSystem: "Linux"
        - displayName: "linux_net9"
          dotnet: "net9.0"
          image: "ADO-UB22-SQL22"
          operatingSystem: "Linux"
        - displayName: "linux_net10"
          dotnet: "net10.0"
          image: "ADO-UB22-SQL22"
          operatingSystem: "Linux"

      manualTestAzureKeyVaultUrl: $(AzureKeyVaultUrl)
      manualTestAzureKeyVaultTenantId: $(AzureKeyVaultTenantId)
      manualTestConnectionStringNpLocalhost: $(ConnectionStringNp_LocalhostDefault_UsernamePassword)
      manualTestConnectionStringTcpLocalhost: $(ConnectionStringTcp_LocalhostDefault_UsernamePassword)
      manualTestConnectionStringNpAzure: $(ConnectionStringNp_Azure_ManagedIdentity)
      manualTestConnectionStringTcpAzure: $(ConnectionStringTcp_Azure_ManagedIdentity)
      manualTestFileStreamDirectory: "$(Pipeline.Workspace)/filestream"
      manualTestLocalDbAppName: $(LocalDbAppName)
      manualTestLocalDbSharedInstanceName: $(LocalDbSharedInstanceName)

  # Stage 3: Collect code coverage
  # @TODO:
