// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

namespace Interop.Windows.Sni
{
    internal enum QueryType
    {
        SNI_QUERY_CONN_INFO,
        SNI_QUERY_CONN_BUFSIZE,
        SNI_QUERY_CONN_KEY,
        SNI_QUERY_CLIENT_ENCRYPT_POSSIBLE,
        SNI_QUERY_SERVER_ENCRYPT_POSSIBLE,
        SNI_QUERY_CERTIFICATE,
        SNI_QUERY_LOCALDB_HMODULE,
        SNI_QUERY_CONN_ENCRYPT,
        SNI_QUERY_CONN_PROVIDERNUM,
        SNI_QUERY_CONN_CONNID,
        SNI_QUERY_CONN_PARENTCONNID,
        SNI_QUERY_CONN_SECPKG,
        SNI_QUERY_CONN_NETPACKETSIZE,
        SNI_QUERY_CONN_NODENUM,
        SNI_QUERY_CONN_PACKETSRECD,
        SNI_QUERY_CONN_PACKETSSENT,
        SNI_QUERY_CONN_PEERADDR,
        SNI_QUERY_CONN_PEERPORT,
        SNI_QUERY_CONN_LASTREADTIME,
        SNI_QUERY_CONN_LASTWRITETIME,
        SNI_QUERY_CONN_CONSUMER_ID,
        SNI_QUERY_CONN_CONNECTTIME,
        SNI_QUERY_CONN_HTTPENDPOINT,
        SNI_QUERY_CONN_LOCALADDR,
        SNI_QUERY_CONN_LOCALPORT,
        SNI_QUERY_CONN_SSLHANDSHAKESTATE,
        SNI_QUERY_CONN_SOBUFAUTOTUNING,
        SNI_QUERY_CONN_SECPKGNAME,
        SNI_QUERY_CONN_SECPKGMUTUALAUTH,
        SNI_QUERY_CONN_CONSUMERCONNID,
        SNI_QUERY_CONN_SNIUCI,
        SNI_QUERY_CONN_SUPPORTS_EXTENDED_PROTECTION,
        SNI_QUERY_CONN_CHANNEL_PROVIDES_AUTHENTICATION_CONTEXT,
        SNI_QUERY_CONN_PEERID,
        SNI_QUERY_CONN_SUPPORTS_SYNC_OVER_ASYNC,
        
        #if NETFRAMEWORK
        SNI_QUERY_CONN_SSL_SECCTXTHANDLE, //why if condition for NETFRAMEWORK?
        #endif
    }
}
