#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################

# Job that performs a build of Microsoft.Data.SqlClient using the build2.proj file.

parameters:
  - name: apiScanDllPath
    type: string

  - name: apiScanPdbPath
    type: string

  - name: publishSymbols
    type: boolean

  - name: signingAppRegistrationClientId
    type: string

  - name: signingAppRegistrationTenantId
    type: string

  - name: signingAuthAkvName
    type: string

  - name: signingAuthSignCertName
    type: string

  - name: signingEsrpClientId
    type: string

  - name: signingEsrpConnectedServiceName
    type: string

  - name: symbolsAzureSubscription
    type: string

  - name: symbolsPublishProjectName
    type: string

  - name: symbolsPublishServer
    type: string

  - name: symbolsPublishTokenUri
    type: string

  - name: symbolsUploadAccount
    type: string

  # Package Dependencies Parameters
  - name: abstractionsArtifactName
    type: string

  - name: abstractionsPackageVersion
    type: string

  - name: loggingArtifactName
    type: string

  - name: loggingPackageVersion
    type: string

  - name: mdsPackageVersion
    type: string

jobs:
  - job: build_package_Mds
    displayName: 'Build Microsoft.Data.SqlClient'
    pool:
      type: windows

    variables:
      ob_outputDirectory: '$(PACK_OUTPUT)'

    steps:
      # Dump environment and parameters
      - template: /eng/pipelines/onebranch/steps/script-output-environment-variables-step.yml@self

      - powershell: |
          $jsonParams = '${{ convertToJson(parameters) }}' -replace '\\', '\\'
          $jsonParams | ConvertFrom-Json | Format-List
        displayName: 'Output Job Parameters'

      # Download Abstractions and Logging packages from previous stages into /packages/ so they
      # are available via the local NuGet feed when restoring.
      # @TODO: With the new build2.proj pack targets, this technically is not necessary.
      - task: DownloadPipelineArtifact@2
        displayName: Download Microsoft.Data.SqlClient.Extensions.Abstractions Artifact
        inputs:
          artifactName: '${{ parameters.abstractionsArtifactName }}'
          targetPath: '$(REPO_ROOT)/packages'

      - task: DownloadPipelineArtifact@2
        displayName: Download Microsoft.Data.SqlClient.Extensions.Logging Artifact
        inputs:
          artifactName: '${{ parameters.loggingArtifactName }}'
          targetPath: '$(REPO_ROOT)/packages'

      # Install the .NET SDK
      - template: /eng/pipelines/steps/install-dotnet.yml@self

      # Perform analysis before building, since this step will clobber build output
      - template: /eng/pipelines/onebranch/steps/roslyn-analyzers-mds-step.yml@self
        parameters:
          abstractionsPackageVersion: '${{ parameters.abstractionsPackageVersion }}'
          loggingPackageVersion: '${{ parameters.loggingPackageVersion }}'
          mdsPackageVersion: '${{ parameters.mdsPackageVersion }}'

      # Perform the actual build
      - template: /eng/pipelines/onebranch/steps/build-mds-step.yml@self
        parameters:
          abstractionsPackageVersion: '${{ parameters.abstractionsPackageVersion }}'
          loggingPackageVersion: '${{ parameters.loggingPackageVersion }}'
          mdsPackageVersion: '${{ parameters.mdsPackageVersion }}'

      # Copy the built DLLs and PDBs to the APIScan output folder for APIScanning post-build
      - template: /eng/pipelines/onebranch/steps/copy-apiscan-files-mds-step.yml@self
        parameters:
          dllPath: '${{ parameters.apiScanDllPath }}'
          pdbPath: '${{ parameters.apiScanPdbPath }}'
          referenceType: 'Package'

      # Sign the DLLs
      - template: /eng/pipelines/onebranch/steps/esrp-dll-signing-step.yml@self
        parameters:
          appRegistrationClientId: '${{ parameters.signingAppRegistrationClientId }}'
          appRegistrationTenantId: '${{ parameters.signingAppRegistrationTenantId }}'
          authAkvName: '${{ parameters.signingAuthAkvName }}'
          authSignCertName: '${{ parameters.signingAuthSignCertName }}'
          esrpClientId: '${{ parameters.signingEsrpClientId }}'
          esrpConnectedServiceName: '${{ parameters.signingEsrpConnectedServiceName }}'
          pattern: 'Microsoft.Data.SqlClient*.dll'

      # Package the build output into a NuGet package
      - template: /eng/pipelines/onebranch/steps/pack-mds-step.yml
        parameters:
          abstractionsPackageVersion: '${{ parameters.abstractionsPackageVersion }}'
          loggingPackageVersion: '${{ parameters.loggingPackageVersion }}'
          mdsPackageVersion: '${{ parameters.mdsPackageVersion }}'

      # Sign the NuGet packages
      - template: /eng/pipelines/onebranch/steps/esrp-nuget-signing-step.yml@self
        parameters:
          appRegistrationClientId: '${{ parameters.signingAppRegistrationClientId }}'
          appRegistrationTenantId: '${{ parameters.signingAppRegistrationTenantId }}'
          authAkvName: '${{ parameters.signingAuthAkvName }}'
          authSignCertName: '${{ parameters.signingAuthSignCertName }}'
          esrpClientId: '${{ parameters.signingEsrpClientId }}'
          esrpConnectedServiceName: '${{ parameters.signingEsrpConnectedServiceName }}'
          searchPath: '$(PACK_OUTPUT)'
          searchPattern: 'Microsoft.Data.SqlClient.*nupkg'

      - ${{ if parameters.publishSymbols }}:
          - template: /eng/pipelines/onebranch/steps/publish-symbols-step.yml@self
            parameters:
              artifactName: 'Microsoft.Data.SqlClient_symbols_$(System.TeamProject)_$(Build.Repository.Name)_$(Build.SourceBranchName)_${{ parameters.mdsPackageVersion }}_$(System.TimelineId)'
              azureSubscription: '${{ parameters.symbolsAzureSubscription }}'
              packageName: 'Microsoft.Data.SqlClient'
              publishProjectName: '${{ parameters.symbolsPublishProjectName }}'
              publishServer: '${{ parameters.symbolsPublishServer }}'
              publishToInternal: true
              publishToPublic: true
              publishTokenUri: '${{ parameters.symbolsPublishTokenUri }}'
              searchPattern: '**/Microsoft.Data.SqlClient*.pdb' # @TODO: This seems very heavy
              uploadAccount: '${{ parameters.symbolsUploadAccount }}'
              version: '${{ parameters.mdsPackageVersion }}'
