#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################

# Job that performs a build of Microsoft.Data.SqlClient using the build2.proj file.

parameters:
  # Whether this build is for an "official" OneBranch pipeline. This is used to enable ESRP signing
  # on the artifacts of this job.
  - name: isOfficial
    type: boolean

  - name: signingAppRegistrationClientId
    type: string

  - name: signingAppRegistrationTenantId
    type: string

  - name: signingAuthAkvName
    type: string

  - name: signingAuthSignCertName
    type: string

  - name: signingEsrpClientId
    type: string

  - name: signingEsrpConnectedServiceName
    type: string

  # Package Parameters
  - name: abstractionsArtifactName
    type: string

  - name: abstractionsPackageVersion
    type: string

  - name: loggingArtifactName
    type: string

  - name: loggingPackageVersion
    type: string

  - name: sqlClientAssemblyFileVersion
    type: string

  - name: sqlClientPackageVersion
    type: string

jobs:
  - job: build_package_SqlClient
    displayName: 'Build Microsoft.Data.SqlClient'
    pool:
      type: windows

    variables:
      ob_outputDirectory: '$(JOB_OUTPUT)'
      ob_sdl_apiscan_softwareFolder: $(JOB_OUTPUT)/assemblies
      ob_sdl_apiscan_symbolsFolder: $(JOB_OUTPUT)/symbols
      ob_sdl_apiscan_softwarename: 'Microsoft.Data.SqlClient'
      ob_sdl_apiscan_versionNumber: ${{ parameters.sqlClientAssemblyFileVersion }}

    steps:
      # Dump environment and parameters
      - template: /eng/pipelines/onebranch/steps/script-output-environment-variables-step.yml@self

      - powershell: |
          $jsonParams = '${{ convertToJson(parameters) }}' -replace '\\', '\\'
          $jsonParams | ConvertFrom-Json | Format-List
        displayName: 'Output Job Parameters'

      # Download Abstractions and Logging packages from previous stages into /packages/ so they
      # are available via the local NuGet feed when restoring.
      # @TODO: With the new build2.proj pack targets, this technically is not necessary.
      - task: DownloadPipelineArtifact@2
        displayName: Download Microsoft.Data.SqlClient.Extensions.Abstractions Artifact
        inputs:
          artifactName: '${{ parameters.abstractionsArtifactName }}'
          targetPath: '$(JOB_INPUT)'

      - task: DownloadPipelineArtifact@2
        displayName: Download Microsoft.Data.SqlClient.Extensions.Logging Artifact
        inputs:
          artifactName: '${{ parameters.loggingArtifactName }}'
          targetPath: '$(JOB_INPUT)'

      # Install the .NET SDK
      - template: /eng/pipelines/steps/install-dotnet.yml@self

      # Perform analysis before building, since this step will clobber build output
      - template: /eng/pipelines/onebranch/steps/roslyn-analyzers-sqlclient-step.yml@self
        parameters:
          abstractionsPackageVersion: '${{ parameters.abstractionsPackageVersion }}'
          loggingPackageVersion: '${{ parameters.loggingPackageVersion }}'
          sqlClientPackageVersion: '${{ parameters.sqlClientPackageVersion }}'

      # Perform the actual build
      - template: /eng/pipelines/onebranch/steps/build-sqlclient-step.yml@self
        parameters:
          abstractionsPackageVersion: '${{ parameters.abstractionsPackageVersion }}'
          loggingPackageVersion: '${{ parameters.loggingPackageVersion }}'
          sqlClientPackageVersion: '${{ parameters.sqlClientPackageVersion }}'

      # Sign the DLLs
      - ${{ if parameters.isOfficial }}:
          - template: /eng/pipelines/onebranch/steps/esrp-dll-signing-step.yml@self
            parameters:
              appRegistrationClientId: '${{ parameters.signingAppRegistrationClientId }}'
              appRegistrationTenantId: '${{ parameters.signingAppRegistrationTenantId }}'
              authAkvName: '${{ parameters.signingAuthAkvName }}'
              authSignCertName: '${{ parameters.signingAuthSignCertName }}'
              esrpClientId: '${{ parameters.signingEsrpClientId }}'
              esrpConnectedServiceName: '${{ parameters.signingEsrpConnectedServiceName }}'
              pattern: 'Microsoft.Data.SqlClient*.dll'

      # Copy DLLs to the assemblies/ subdirectory for APIScan.
      - task: CopyFiles@2
        displayName: Copy DLLs for APIScan
        inputs:
          SourceFolder: '$(BUILD_OUTPUT)/Microsoft.Data.SqlClient/Package-Release'
          Contents: '**/Microsoft.Data.SqlClient.dll'
          TargetFolder: '$(JOB_OUTPUT)/assemblies'
          flattenFolders: false

      # Copy PDBs into the output directory so they are included in the published pipeline
      # artifact. The symbols publishing stage will download this artifact and publish PDBs
      # for this package using the files under symbols/.
      - task: CopyFiles@2
        displayName: Copy PDBs for APIScan and Symbols Publishing
        inputs:
          SourceFolder: '$(BUILD_OUTPUT)/Microsoft.Data.SqlClient/Package-Release'
          Contents: '**/Microsoft.Data.SqlClient*.pdb'
          TargetFolder: '$(JOB_OUTPUT)/symbols'
          flattenFolders: false

      # Package the build output into a NuGet package
      - template: /eng/pipelines/onebranch/steps/pack-sqlclient-step.yml
        parameters:
          abstractionsPackageVersion: '${{ parameters.abstractionsPackageVersion }}'
          loggingPackageVersion: '${{ parameters.loggingPackageVersion }}'
          sqlClientPackageVersion: '${{ parameters.sqlClientPackageVersion }}'

      # Sign the NuGet packages
      - ${{ if parameters.isOfficial }}:
          - template: /eng/pipelines/onebranch/steps/esrp-nuget-signing-step.yml@self
            parameters:
              appRegistrationClientId: '${{ parameters.signingAppRegistrationClientId }}'
              appRegistrationTenantId: '${{ parameters.signingAppRegistrationTenantId }}'
              authAkvName: '${{ parameters.signingAuthAkvName }}'
              authSignCertName: '${{ parameters.signingAuthSignCertName }}'
              esrpClientId: '${{ parameters.signingEsrpClientId }}'
              esrpConnectedServiceName: '${{ parameters.signingEsrpConnectedServiceName }}'
              searchPath: '$(JOB_OUTPUT)/packages'
              searchPattern: 'Microsoft.Data.SqlClient.*nupkg'
