#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################
parameters:
  - name: symbolsFolder
    type: string
    default: symbols

  - name: softwareFolder
    type: string
    default: software

  - name: publishSymbols
    type: boolean

  - name: isPreview
    type: boolean

jobs:
- job: build_signed_package
  displayName: 'Build Signed MDS Package'
  pool:
    type: windows  # read more about custom job pool types at https://aka.ms/obpipelines/yaml/jobs

  variables:
  - template: /eng/pipelines/libraries/variables.yml@self
  - ${{ if parameters.isPreview }}:
    - name: abstractionsPackageVersion
      value: $(abstractionsPackagePreviewVersion)
    - name: mdsPackageVersion
      value: $(previewMdsPackageVersion)

  steps:
  - script: SET
    displayName: 'Print Environment Variables'

  - pwsh: |
      Write-Host "##vso[task.setvariable variable=CDP_BUILD_TYPE_COPY;isOutput=true]$($env:CDP_BUILD_TYPE)"
    displayName: Get Build Type

  # Install the .NET SDK.
  - template: /eng/pipelines/steps/install-dotnet.yml@self

  # Install the .NET SDK.
  - template: /eng/pipelines/steps/install-dotnet.yml@self

  # Build our tooling, which is required by the analysis step below, but
  # shouldn't be analyzed itself.
  - task: MSBuild@1
    displayName: 'Build Tooling'
    inputs:
      solution: '**/build.proj'
      configuration: Release
      msbuildArguments: -t:BuildTools

  # Perform analysis before building, since this step will clobber build output.
  - template: /eng/pipelines/common/templates/steps/code-analyze-step.yml@self

  # Build MDS, producing signed DLLs.
  - template: /eng/pipelines/common/templates/steps/build-all-configurations-signed-dlls-step.yml@self
    parameters:
      # These variables are sourced from common-variables.yml.
      abstractionsAssemblyFileVersion: $(abstractionsAssemblyFileVersion)
      abstractionsPackageVersion: $(abstractionsPackageVersion)
      mdsAssemblyFileVersion: $(mdsAssemblyFileVersion)
      mdsPackageVersion: $(mdsPackageVersion)

  - template: /eng/pipelines/common/templates/steps/esrp-code-signing-step.yml@self
    parameters:
      artifactType: dll

  - template: /eng/pipelines/common/templates/steps/generate-nuget-package-step.yml@self
    parameters:
      buildConfiguration: Release
      displayName: 'Create MDS NuGet Package'
      installNuget: false
      nuspecPath: $(nuspecPath)
      outputDirectory: $(artifactDirectory)
      packageVersion: $(mdsPackageVersion)
      properties: 'AbstractionsPackageVersion=$(abstractionsPackageVersion)'
      referenceType: Package

  - template: /eng/pipelines/common/templates/steps/esrp-code-signing-step.yml@self
    parameters:
      artifactType: pkg

  - template: /eng/pipelines/common/templates/steps/copy-dlls-for-test-step.yml@self

  # Publish symbols to servers
  - ${{ if eq(parameters.publishSymbols, true) }}:
    - template: /eng/pipelines/common/templates/steps/publish-symbols-step.yml@self
      parameters:
        symbolsArtifactName: mds_symbols_$(System.TeamProject)_$(Build.Repository.Name)_$(Build.SourceBranchName)_$(mdsPackageVersion)_$(System.TimelineId)
