#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################

# This template is only used in the MDS Official pipeline.

parameters:

  - name: isPreview
    type: boolean

  # The value we will set as the ob_outputDirectory variable, required by the OneBranch templates.
  # level.
  - name: onebranchOutputDirectory
    type: string

  - name: publishSymbols
    type: boolean

  - name: softwareFolder
    type: string
    default: software

  - name: symbolsFolder
    type: string
    default: symbols

jobs:
- job: build_signed_package
  displayName: 'Build Signed MDS Package'
  pool:
    type: windows  # read more about custom job pool types at https://aka.ms/obpipelines/yaml/jobs

  variables:

  # Bring in Abstractions version variables, and give them unique names for our purposes.
  - template: /eng/pipelines/abstractions/onebranch/variables.yml@self

  - name: abstractionsAssemblyFileVersion
    value: $(assemblyFileVersion)

  - name: abstractionsPackageVersion
    value: $(packageVersion)

  # The OneBranch templates require that the $(ob_outputDirectory) variable be defined at every job
  # level.
  - name: ob_outputDirectory
    value: ${{ parameters.onebranchOutputDirectory }}

  - ${{ if parameters.isPreview }}:
    - name: mdsPackageVersion
      value: $(previewMdsPackageVersion)

  steps:
  - script: SET
    displayName: 'Print Environment Variables'

  - pwsh: |
      Write-Host "##vso[task.setvariable variable=CDP_BUILD_TYPE_COPY;isOutput=true]$($env:CDP_BUILD_TYPE)"
    # This variable is used far away in validate-signed-packages-job.yml.
    name: GetBuildType
    displayName: Get Build Type

  # Install the .NET SDK.
  - template: /eng/pipelines/steps/install-dotnet.yml@self

  # Perform analysis before building, since this step will clobber build output.
  - template: /eng/pipelines/common/templates/steps/code-analyze-step.yml@self

  # Build MDS, producing signed DLLs.
  - template: /eng/pipelines/common/templates/steps/build-all-configurations-signed-dlls-step.yml@self
    parameters:
      # These variables are sourced from common-variables.yml.
      abstractionsAssemblyFileVersion: $(abstractionsAssemblyFileVersion)
      abstractionsPackageVersion: $(abstractionsPackageVersion)
      mdsAssemblyFileVersion: $(mdsAssemblyFileVersion)
      mdsPackageVersion: $(mdsPackageVersion)

  - template: /eng/pipelines/common/templates/steps/esrp-code-signing-step.yml@self
    parameters:
      artifactType: dll

  - template: /eng/pipelines/common/templates/steps/generate-nuget-package-step.yml@self
    parameters:
      buildConfiguration: Release
      displayName: 'Create MDS NuGet Package'
      installNuget: false
      nuspecPath: $(nuspecPath)
      outputDirectory: $(artifactDirectory)
      packageVersion: $(mdsPackageVersion)
      properties: 'AbstractionsPackageVersion=$(abstractionsPackageVersion)'
      referenceType: Package

  - template: /eng/pipelines/common/templates/steps/esrp-code-signing-step.yml@self
    parameters:
      artifactType: pkg

  - template: /eng/pipelines/common/templates/steps/copy-dlls-for-test-step.yml@self

  # Publish symbols to servers
  - ${{ if eq(parameters.publishSymbols, true) }}:
    - template: /eng/pipelines/common/templates/steps/publish-symbols-step.yml@self
      parameters:
        symbolsArtifactName: mds_symbols_$(System.TeamProject)_$(Build.Repository.Name)_$(Build.SourceBranchName)_$(mdsPackageVersion)_$(System.TimelineId)
