#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################

# This file is only included in MDS OneBranch Official pipelines.

parameters:
  # The directory to copy PDB files into for ApiScan to inspect.
  - name: symbolsFolder
    type: string
    default: symbols

  # The directory to copy DLL files into for ApiScan to inspect.
  - name: softwareFolder
    type: string
    default: software

  # True to publish symbols to public and private feeds after the build completes.
  - name: publishSymbols
    type: boolean

  # True if this is a preview build, which uses the preview version numbers from
  # common-variables.yml.
  - name: isPreview
    type: boolean

jobs:
- job: build_package_SqlClient
  displayName: 'Build Microsoft.Data.SqlClient'
  pool:
    type: windows  # read more about custom job pool types at https://aka.ms/obpipelines/yaml/jobs

  variables:
  - ${{ if parameters.isPreview }}:
    - name: abstractionsPackageVersion
      value: $(abstractionsPackagePreviewVersion)
    - name: loggingPackageVersion
      value: $(loggingPackagePreviewVersion)
    - name: mdsPackageVersion
      value: $(previewMdsPackageVersion)

  steps:
  - script: SET
    displayName: 'Print Environment Variables'

  - pwsh: |
      Write-Host "##vso[task.setvariable variable=CDP_BUILD_TYPE_COPY;isOutput=true]$($env:CDP_BUILD_TYPE)"
    # This variable is used far away in validate-signed-packages-job.yml.
    name: GetBuildType
    displayName: Get Build Type

  # Download the Abstractions and Logging packages from the previous stage into
  # packages/ so that they're available via the local NuGet feed when restoring MDS.
  # MDS depends on both Extensions.Abstractions and Extensions.Logging.
  - task: DownloadPipelineArtifact@2
    displayName: Download Abstractions Package
    inputs:
      artifactName: $(abstractionsArtifactsName)
      targetPath: $(Build.SourcesDirectory)/packages

  - task: DownloadPipelineArtifact@2
    displayName: Download Logging Package
    inputs:
      artifactName: $(loggingArtifactsName)
      targetPath: $(Build.SourcesDirectory)/packages

  # Install the .NET SDK.
  - template: /eng/pipelines/steps/install-dotnet.yml@self

  # Build our tooling, which is required by the analysis step below, but
  # shouldn't be analyzed itself.
  - task: MSBuild@1
    displayName: 'Build Tooling'
    inputs:
      solution: '**/build.proj'
      configuration: Release
      msbuildArguments: -t:BuildTools

  # Perform analysis before building, since this step will clobber build output.
  - template: /eng/pipelines/common/templates/steps/code-analyze-step.yml@self

  # Build MDS, producing signed DLLs.
  - template: /eng/pipelines/common/templates/steps/build-all-configurations-signed-dlls-step.yml@self
    parameters:
      # These variables are sourced from common-variables.yml.
      abstractionsAssemblyFileVersion: $(abstractionsAssemblyFileVersion)
      abstractionsPackageVersion: $(abstractionsPackageVersion)
      loggingAssemblyFileVersion: $(loggingAssemblyFileVersion)
      loggingPackageVersion: $(loggingPackageVersion)
      mdsAssemblyFileVersion: $(mdsAssemblyFileVersion)
      mdsPackageVersion: $(mdsPackageVersion)

  - template: /eng/pipelines/common/templates/steps/esrp-code-signing-step.yml@self
    parameters:
      artifactType: dll

  - template: /eng/pipelines/common/templates/steps/generate-nuget-package-step.yml@self
    parameters:
      buildConfiguration: Release
      displayName: 'Create MDS NuGet Package'
      generateSymbolsPackage: true
      installNuget: false
      nuspecPath: $(nuspecPath)
      outputDirectory: $(artifactDirectory)
      packageVersion: $(mdsPackageVersion)
      properties: 'AbstractionsPackageVersion=$(abstractionsPackageVersion);LoggingPackageVersion=$(loggingPackageVersion)'
      referenceType: Package

  - template: /eng/pipelines/common/templates/steps/esrp-code-signing-step.yml@self
    parameters:
      artifactType: pkg

  # Copy DLLs and PDBs to the software and symbols folders for APIScan and testing.
  - template: /eng/pipelines/common/templates/steps/copy-dlls-for-test-step.yml@self
    parameters:
      softwareFolder: '${{ parameters.softwareFolder }}'
      symbolsFolder: '${{ parameters.symbolsFolder }}'

  # Publish symbols to servers
  - ${{ if eq(parameters.publishSymbols, true) }}:
    - template: /eng/pipelines/common/templates/steps/publish-symbols-step.yml@self
      parameters:
        symbolsArtifactName: mds_symbols_$(System.TeamProject)_$(Build.Repository.Name)_$(Build.SourceBranchName)_$(mdsPackageVersion)_$(System.TimelineId)
