#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################
parameters:
  - name: symbolsFolder
    type: string
    default: symbols

  - name: softwareFolder
    type: string
    default: software

  - name: publishSymbols
    type: boolean

  - name: isPreview
    type: boolean

jobs:
- job: build_signed_package
  displayName: 'Build Signed MDS Package'
  pool:
    type: windows  # read more about custom job pool types at https://aka.ms/obpipelines/yaml/jobs
    
  variables:
  - template: ../../../libraries/variables.yml@self
  - ${{ if parameters.isPreview }}:
    - name: abstractionsPackageVersion
      value: $(abstractionsPackagePreviewVersion)
    - name: mdsPackageVersion
      value: $(previewMdsPackageVersion)

  steps:
  - script: SET
    displayName: 'Print Environment Variables'

  - powershell: |
      Write-Host "##vso[task.setvariable variable=CDP_BUILD_TYPE_COPY;isOutput=true]$($env:CDP_BUILD_TYPE)"
    name: GetBuildType

  # Build our tooling, which is required by the analysis step below, but
  # shouldn't be analyzed itself.
  - task: MSBuild@1
    displayName: 'Build Tooling'
    inputs:
      solution: '**/build.proj'
      configuration: $(Configuration)
      msbuildArguments: -t:BuildTools

  # Perform analysis before building, since this step will clobber build output.
  - template: ../steps/code-analyze-step.yml@self
  
  # Update the root NuGet.config to use the packages/ directory as a source.
  # When we build MDS in Package mode, it depends on the Abstractions package,
  # which we will build and package into packages/.
  - template: ../steps/update-nuget-config-local-feed-step.yml
    parameters:
      packagePath: $(REPOROOT)/packages
  
  # Build the Abstractions package.
  - task: MSBuild@1
    displayName: Build Abstractions
    inputs:
      solution: '**/build.proj'
      configuration: $(Configuration)
      msbuildArguments: -t:BuildAbstractions

  # Build MDS in Package mode, producing signed DLLs.
  - template: ../steps/build-all-configurations-signed-dlls-step.yml@self
    parameters:
      # These variables are sourced from common-variables.yml.
      abstractionsAssemblyFileVersion: $(abstractionsAssemblyFileVersion)
      abstractionsPackageVersion: $(abstractionsPackageVersion)
      configuration: $(Configuration)
      mdsAssemblyFileVersion: $(mdsAssemblyFileVersion)
      mdsPackageVersion: $(mdsPackageVersion)
      referenceType: Package

  - template: ../steps/esrp-code-signing-step.yml@self
    parameters:
      artifactType: dll
  
  - template: ../steps/generate-nuget-package-step.yml@self
    parameters:
      nuspecPath: $(nuspecPath)
      packageVersion: $(mdsPackageVersion)
      outputDirectory: $(artifactDirectory)
      displayName: 'Create MDS NuGet Package'
      referenceType: Package
      properties: 'AbstractionsPackageVersion=$(abstractionsPackageVersion)'
  
  - template: ../steps/esrp-code-signing-step.yml@self
    parameters:
      artifactType: pkg
  
  - template: ../steps/copy-dlls-for-test-step.yml@self
    parameters:
      product: MDS

  # Publish symbols to servers
  - template: ../steps/publish-symbols-step.yml@self
    parameters:
      publishSymbols: ${{ parameters['PublishSymbols'] }}
      symbolsArtifactName: mds_symbols_$(System.TeamProject)_$(Build.Repository.Name)_$(Build.SourceBranchName)_$(mdsPackageVersion)_$(System.TimelineId)
