#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################
parameters:

  - name: 'debug'
    type: boolean
    default: false
  
  - name: referenceType
    type: string
    values:
      - Package
      - Project

  - name: poolName
    type: string
    default: $(ci_var_defaultPoolName)

  - name: imageOverride
    type: string
    default: ADO-MMS22-SQL19

  - name: abstractionsArtifactName
    type: string
    default: Abstractions.Artifact

  - name: mdsArtifactName
    type: string
    default: MDS.Artifact
  
  - name: platform
    type: string
    default: $(Platform)
  
  - name: configuration
    type: string
    default: $(Configuration)

  - name: prebuildSteps
    type: stepList
    default: []

  - name: abstractionsPackageVersion
    type: string

  - name: mdsPackageVersion
    type: string

jobs:
- job: build_mds_akv_packages_job
  displayName: Build MDS & AKV Packages

  pool:
    name: ${{parameters.poolName }}
    demands:
    - imageOverride -equals ${{ parameters.imageOverride }}
    - msbuild

  variables:
    - template: ../../../libraries/ci-build-variables.yml@self

  steps:
  - ${{ if ne(parameters.prebuildSteps, '') }}:
    - ${{ parameters.prebuildSteps }} # extra steps to run before the build like downloading sni and the required configuration

  # If we're testing in Package mode, download the Abstractions package artifacts into packages/,
  # and then setup the top-level NuGet.config to look in packages/ for local
  # NuGet dependencies.
  - ${{ if eq(parameters.referenceType, 'Package') }}:
    - task: DownloadPipelineArtifact@2
      displayName: Download Abstractions Package Artifact
      inputs:
        artifactName: ${{ parameters.abstractionsArtifactName }}
        targetPath: $(packagePath)
    # Note that packages/ will have been created by the above step, which is a
    # pre-requisite for configuring NuGet.
    - template: ../steps/ci-prebuild-step.yml@self
      parameters:
        debug: ${{ parameters.debug }}
        referenceType: ${{ parameters.referenceType }}

  - template: ../steps/ci-project-build-step.yml@self
    parameters:
      platform: ${{ parameters.platform }}
      configuration: ${{ parameters.configuration }}
      referenceType: ${{ parameters.referenceType }}
      operatingSystem: Windows
      build: MDS
      abstractionsPackageVersion: ${{parameters.abstractionsPackageVersion}}

  - template: ../steps/generate-nuget-package-step.yml@self
    parameters:
      packageVersion: ${{ parameters.mdsPackageVersion }}
      configuration: $(Configuration)
      nuspecPath: 'tools/specs/Microsoft.Data.SqlClient.nuspec'
      outputDirectory: $(packagePath)
      generateSymbolsPackage: false
      referenceType: ${{ parameters.referenceType }}
      properties: 'AbstractionsPackageVersion=${{ parameters.abstractionsPackageVersion }}'
      displayName: 'Create MDS NuGet Package'

  - template: ../steps/ci-project-build-step.yml@self
    parameters:
      platform: ${{ parameters.platform }}
      configuration: ${{ parameters.configuration }}
      referenceType: ${{ parameters.referenceType }}
      operatingSystem: Windows
      build: AKV
      mdsPackageVersion: ${{parameters.mdsPackageVersion}}

  - template: ../steps/generate-nuget-package-step.yml@self
    parameters:
      packageVersion: $(akvPackageVersion)
      configuration: $(Configuration)
      nuspecPath: 'tools/specs/add-ons/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.nuspec'
      outputDirectory: $(packagePath)
      generateSymbolsPackage: false
      referenceType: ${{ parameters.referenceType }}
      properties: 'MdsPackageVersion=${{ parameters.mdsPackageVersion }}'
      installNuget: false
      displayName: 'Create AKV NuGet Package'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Pipeline Artifact'
    inputs:
      targetPath: $(packagePath)
      artifactName: ${{ parameters.mdsArtifactName }}
