#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################
parameters:

  # Debug.
  - name: debug
    type: boolean
    default: false

  # Reference Type.
  - name: referenceType
    type: string
    values:
      - Package
      - Project

  # Pool Name.
  - name: poolName
    type: string
    default: $(ci_var_defaultPoolName)

  # Image Override.
  - name: imageOverride
    type: string
    default: ADO-MMS22-SQL19

  # Abstractions Artifacts Name.
  - name: abstractionsArtifactsName
    type: string
    default: Abstractions.Artifacts

  # Logging Artifacts Name.
  - name: loggingArtifactsName
    type: string
    default: Logging.Artifacts

  # Mds Artifacts Name.
  - name: mdsArtifactsName
    type: string
    default: MDS.Artifacts

  # Platform.
  - name: platform
    type: string
    default: $(Platform)

  # Build Configuration.
  - name: buildConfiguration
    type: string
    values:
      - Debug
      - Release

  # Prebuild Steps.
  - name: prebuildSteps
    type: stepList
    default: []

  # Abstractions Package Version.
  - name: abstractionsPackageVersion
    type: string

  # Logging Package Version.
  - name: loggingPackageVersion
    type: string

  # Mds Package Version.
  - name: mdsPackageVersion
    type: string

  # Assembly Build Number.
  - name: assemblyBuildNumber
    type: string

jobs:
- job: build_mds_akv_packages_job
  displayName: Build MDS & AKV Packages

  pool:
    name: ${{parameters.poolName }}
    demands:
    - imageOverride -equals ${{ parameters.imageOverride }}
    - msbuild

  variables:
    - template: /eng/pipelines/libraries/ci-build-variables.yml@self

  steps:
  - ${{ if eq(parameters.debug, true)}}:
    - powershell: |
        Get-ChildItem env: | Sort-Object Name
      displayName: '[Debug] List Environment Variables'

  - ${{ if ne(parameters.prebuildSteps, '') }}:
     # Extra steps to run before the build like downloading sni and the required
     # configuration
    - ${{ parameters.prebuildSteps }}

  # If we're testing in Package mode, then we must download the Abstractions and
  # Logging package artifacts.
  - ${{ if eq(parameters.referenceType, 'Package') }}:
    - task: DownloadPipelineArtifact@2
      displayName: Download Abstractions Package Artifacts
      inputs:
        artifactName: ${{ parameters.abstractionsArtifactsName }}
        targetPath: $(packagePath)

    - task: DownloadPipelineArtifact@2
      displayName: Download Logging Package Artifacts
      inputs:
        artifactName: ${{ parameters.loggingArtifactsName }}
        targetPath: $(packagePath)

  # Install the .NET SDK.
  - template: /eng/pipelines/steps/install-dotnet.yml@self

  # When we're performing a Debug build, we still want to try _compiling_ the
  # code in Release mode to ensure downstream pipelines don't encounter
  # compilation errors.  We won't use the Release artifacts for anything else
  # though.
  - ${{ if eq(parameters.buildConfiguration, 'Debug') }}:
    - template: /eng/pipelines/common/templates/steps/ci-project-build-step.yml@self
      parameters:
        platform: ${{ parameters.platform }}
        buildConfiguration: Release
        referenceType: Project
        build: all
        assemblyBuildNumber: ${{ parameters.assemblyBuildNumber }}

  - template: /eng/pipelines/common/templates/steps/ci-project-build-step.yml@self
    parameters:
      platform: ${{ parameters.platform }}
      buildConfiguration: ${{ parameters.buildConfiguration }}
      referenceType: ${{ parameters.referenceType }}
      operatingSystem: Windows
      build: MDS
      abstractionsPackageVersion: ${{parameters.abstractionsPackageVersion}}
      loggingPackageVersion: ${{ parameters.loggingPackageVersion }}
      mdsPackageVersion: ${{ parameters.mdsPackageVersion }}
      assemblyBuildNumber: ${{ parameters.assemblyBuildNumber }}

  - template: /eng/pipelines/common/templates/steps/generate-nuget-package-step.yml@self
    parameters:
      buildConfiguration: ${{ parameters.buildConfiguration }}
      displayName: 'Create MDS NuGet Package'
      generateSymbolsPackage: true
      nuspecPath: 'tools/specs/Microsoft.Data.SqlClient.nuspec'
      outputDirectory: $(packagePath)
      packageVersion: ${{ parameters.mdsPackageVersion }}
      properties: 'AbstractionsPackageVersion=${{ parameters.abstractionsPackageVersion }};LoggingPackageVersion=${{ parameters.loggingPackageVersion }}'
      referenceType: ${{ parameters.referenceType }}

  - template: /eng/pipelines/common/templates/steps/ci-project-build-step.yml@self
    parameters:
      platform: ${{ parameters.platform }}
      buildConfiguration: ${{ parameters.buildConfiguration }}
      referenceType: ${{ parameters.referenceType }}
      operatingSystem: Windows
      build: AKV
      mdsPackageVersion: ${{ parameters.mdsPackageVersion }}
      assemblyBuildNumber: ${{ parameters.assemblyBuildNumber }}

  - template: /eng/pipelines/common/templates/steps/generate-nuget-package-step.yml@self
    parameters:
      buildConfiguration: ${{ parameters.buildConfiguration }}
      displayName: 'Create AKV NuGet Package'
      generateSymbolsPackage: true
      installNuget: false
      nuspecPath: 'tools/specs/add-ons/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.nuspec'
      outputDirectory: $(packagePath)
      packageVersion: $(akvPackageVersion)
      properties: 'MdsPackageVersion=${{ parameters.mdsPackageVersion }}'
      referenceType: ${{ parameters.referenceType }}

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Pipeline Artifacts'
    inputs:
      targetPath: $(packagePath)
      artifactName: ${{ parameters.mdsArtifactsName }}
