#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################

# This job processes code coverage reports generated during test runs,
# merges them, generates code coverage reports, publishes them to the
# pipeline, and uploads them to CodeCov.

parameters:
  
  # True to include debug steps.
  - name: debug
    type: boolean
    default: false

  # The pool image to use.
  - name: image
    type: string

  # The agent pool name.
  - name: pool
    type: string

  # Array of target frameworks to process code coverage for:
  #
  #   e.g. [net462, net8.0, net9.0]
  #
  - name: targetFrameworks
    type: object

  # True to upload code coverage results to CodeCov.
  - name: upload
    type: boolean

jobs:
  - job: CodeCoverage
    displayName: Publish Code Coverage

    pool:
      name: ${{ parameters.pool }}
      ${{ if eq(parameters.pool, 'Azure Pipelines') }}:
        vmImage: ${{ parameters.image }}
      ${{ else }}:
        demands:
        - imageOverride -equals ${{ parameters.image }}

    variables:
      netFxDir: $(Build.SourcesDirectory)\coverageNetFx
      netCoreDir: $(Build.SourcesDirectory)\coverageNetCore

    steps:
      - ${{if eq(parameters.debug, true)}}:
        - pwsh: |
            Get-ChildItem env: | Sort-Object Name
          displayName: '[Debug] List Environment Variables [debug]'

        - pwsh: Get-Volume
          displayName: '[Debug] Show Disk Usage'

      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          packageType: sdk
          useGlobalJson: true

      - pwsh: |
          dotnet tool install --global dotnet-coverage
          dotnet tool install --global dotnet-reportgenerator-globaltool
        displayName: Install dotnet tools
              
      - ${{ each targetFramework in parameters.targetFrameworks }}:
        - task: DownloadPipelineArtifact@2
          displayName: 'Download Coverage Reports [${{ targetFramework }}]'
          inputs:
            itemPattern: '**\${{ targetFramework }}*'
            ${{ if startsWith(targetFramework, 'net4') }}:
              targetPath: $(netFxDir)
            ${{ else }}:
              targetPath: $(netCoreDir)

      - ${{if eq(parameters.debug, true)}}:
        - pwsh: Get-Volume
          displayName: '[Debug] Show Disk Usage'

        - pwsh: Get-ChildItem $(netFxDir) -Recurse -File -Filter *.coverage
          displayName: '[Debug] List coverageNetFx files'

        - pwsh: Get-ChildItem $(netCoreDir) -Recurse -File -Filter *.coverage
          displayName: '[Debug] List coverageNetCore files'

      - pwsh: |
          function MergeFiles {
            param(
            [string]$InputDirectoryPath,
            [string]$OutputDirectoryName
            )

            $files = Get-ChildItem $InputDirectoryPath -Recurse -File -Filter *.coverage

            # echo $files
            mkdir $OutputDirectoryName
            $counter=0
            $toProcess = @()

            foreach ($file in $files) {
                $toProcess += @{ 
                    File = $file.FullName
                    OutputFile = "$OutputDirectoryName\$counter.coveragexml"
                }

                $counter++
            }

            $jobs = @()
            foreach ($file in $toProcess){
                $jobs += Start-ThreadJob -ScriptBlock { 
                    $params = $using:file
                    & dotnet-coverage merge $($params.File) --output $($params.OutputFile) --output-format xml 
                } 
            }

            Write-Host "Merging started..."
            Wait-Job -Job $jobs

            foreach ($job in $jobs) {
                Receive-Job -Job $job -Wait -AutoRemoveJob
            }
          }

          MergeFiles -InputDirectoryPath "$(netFxDir)" -OutputDirectoryName "coverageNetFxXml"
          MergeFiles -InputDirectoryPath "$(netCoreDir)" -OutputDirectoryName "coverageNetCoreXml"
          
          Write-Host "Removing original coverage files..."
          Remove-Item $(netFxDir) -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item $(netCoreDir) -Recurse -Force -ErrorAction SilentlyContinue
        displayName: Convert coverage files to xml

      - ${{if eq(parameters.debug, true)}}:
        - pwsh: Get-Volume
          displayName: '[Debug] Show Disk Usage'

        - pwsh: |
            dir coverageNetFxXml\
            dir coverageNetCoreXml\
          displayName: '[Debug] List converted files'

      - pwsh: |
          $jobs = @()
          $jobs += Start-ThreadJob -ScriptBlock { 
              & reportgenerator "-reports:coverageNetFxXml\*.coveragexml" "-targetdir:coveragereportNetFx" "-reporttypes:Cobertura;" "-assemblyfilters:+microsoft.data.sqlclient.dll" "-sourcedirs:$(Build.SourcesDirectory)\src\Microsoft.Data.SqlClient\netfx\src;$(Build.SourcesDirectory)\src\Microsoft.Data.SqlClient\src" "-classfilters:+Microsoft.Data.*"
          }

          $jobs += Start-ThreadJob -ScriptBlock { 
              & reportgenerator "-reports:coverageNetCoreXml\*.coveragexml" "-targetdir:coveragereportNetCore" "-reporttypes:Cobertura;" "-assemblyfilters:+microsoft.data.sqlclient.dll" "-sourcedirs:$(Build.SourcesDirectory)\src\Microsoft.Data.SqlClient\netcore\src;$(Build.SourcesDirectory)\src\Microsoft.Data.SqlClient\src" "-classfilters:+Microsoft.Data.*"
          }

          $jobs += Start-ThreadJob -ScriptBlock { 
              & reportgenerator "-reports:coverageNetCoreXml\*.coveragexml" "-targetdir:coveragereportAddOns" "-reporttypes:Cobertura;" "-assemblyfilters:+microsoft.data.sqlclient.alwaysencrypted.azurekeyvaultprovider.dll" "-sourcedirs:$(Build.SourcesDirectory)\src\Microsoft.Data.SqlClient\add-ons\AzureKeyVaultProvider" "-classfilters:+Microsoft.Data.*"
          }

          Write-Host "Running ReportGenerator..."
          Wait-Job -Job $jobs

          foreach ($job in $jobs) {
              Receive-Job -Job $job -Wait -AutoRemoveJob
          }

          Write-Host "Removing merged XML files..."
          Remove-Item coverageNetFxXml -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item coverageNetCoreXml -Recurse -Force -ErrorAction SilentlyContinue
        displayName: Run ReportGenerator

      - ${{if eq(parameters.debug, true)}}:
        - pwsh: Get-Volume
          displayName: '[Debug] Show Disk Usage'

      - task: PublishCodeCoverageResults@2
        displayName: Publish code coverage results
        inputs:
          summaryFileLocation: '*\Cobertura.xml'

      - ${{if eq(parameters.upload, true)}}:
        - pwsh: |
            #download Codecov CLI
            $ProgressPreference = 'SilentlyContinue' 
            Invoke-WebRequest -Uri https://cli.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe
            
            ./codecov --verbose upload-process --fail-on-error -t $(CODECOV_TOKEN) -f "coveragereportNetFx\Cobertura.xml" -F netfx
            ./codecov --verbose upload-process --fail-on-error -t $(CODECOV_TOKEN) -f "coveragereportNetCore\Cobertura.xml" -F netcore
            ./codecov --verbose upload-process --fail-on-error -t $(CODECOV_TOKEN) -f "coveragereportAddOns\Cobertura.xml" -F addons
          displayName: Upload to CodeCov
