#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################
parameters:
  - name: abstractionsArtifactsName
    type: string

  - name: abstractionsPackageVersion
    type: string

  - name: configProperties
    type: object
    default: {} # - key: 'value'

  - name: configSqlFor
    type: string # local, azure, or enclave
    default: local

  - name: debug
    type: boolean
    default: false

  - name: enableX64Test
    type: boolean
    default: true

  - name: enableX86Test
    type: boolean
    default: false

  - name: hostedPool
    type: boolean
    default: false

  - name: image
    type: string

  - name: jobDisplayName
    type: string

  - name: mdsArtifactsName
    type: string

  - name: mdsPackageVersion
    type: string

  - name: netcoreVersionTestUtils
    type: string

  - name: operatingSystem
    type: string
    values:
      - Linux
      - Mac
      - Windows
    default: Windows

  - name: buildConfiguration
    type: string
    values:
      - Debug
      - Release

  - name: poolName
    type: string

  - name: prebuildSteps
    type: stepList
    default: []

  - name: publishTestResults
    type: boolean
    default: false

  - name: referenceType
    type: string
    values:
      - Project
      - Package

  - name: targetFramework
    type: string

  - name: testSet
    type: string

  # The timeout, in minutes, for this job.
  - name: timeout
    type: number

  # True if this is an ARM64 job.
  - name: isArm64
    type: boolean
    default: false

  - name: usemanagedSNI
    type: boolean
    default: false

jobs:
- job: ${{ format('{0}', coalesce(parameters.jobDisplayName, parameters.image, 'unknown_image')) }}

  # Some of our tests take longer than the default 60 minutes to run on some
  # OSes and configurations.
  timeoutInMinutes: ${{ parameters.timeout }}

  pool:
    name: '${{ parameters.poolName }}'
    ${{ if eq(parameters.hostedPool, true) }}:
      vmImage: ${{ parameters.image }}
    ${{ else }}:
      demands:
      - imageOverride -equals ${{ parameters.image }}

  variables:
    - name: dotnetx86RootPath
      value: '$(dotnetx86Path)'

  steps:

  # If we're testing in Package mode, download the Abstractions and MDS package
  # artifacts and put them in the packages/ directory in the repo root.
  - ${{ if eq(parameters.referenceType, 'Package') }}:
    - task: DownloadPipelineArtifact@2
      displayName: Download Abstractions Package Artifacts
      inputs:
        artifactName: ${{ parameters.abstractionsArtifactsName }}
        targetPath: $(Build.SourcesDirectory)/packages

    - task: DownloadPipelineArtifact@2
      displayName: Download MDS Package Artifacts
      inputs:
        artifactName: ${{ parameters.mdsArtifactsName }}
        targetPath: $(Build.SourcesDirectory)/packages

  # Install the .NET SDK and Runtimes.
  - template: /eng/pipelines/steps/install-dotnet.yml@self
    parameters:
      debug: ${{ parameters.debug }}
      ${{ if parameters.isArm64 }}:
        architecture: arm64
        # ARM64 needs to specify slightly different runtime version formats.
        # See the install-dotnet template docs for more info.
        runtimes: ['8.0', '9.0']
      ${{ else }}:
        runtimes: [8.x, 9.x]

  - ${{ if ne(parameters.prebuildSteps, '') }}:
    - ${{ parameters.prebuildSteps }} # extra steps to run before the build like downloading sni and the required configuration

  - ${{ if eq(parameters.referenceType, 'Project') }}:
    - template: ../steps/ci-project-build-step.yml@self
      parameters:
        build: allNoDocs
        buildConfiguration: ${{ parameters.buildConfiguration }}
        referenceType: ${{ parameters.referenceType }}
        mdsPackageVersion: ${{ parameters.mdsPackageVersion }}

  # Pipelines running via forks of the repo won't have access to secrets brought in from Azure
  # DevOps Library groups.  This includes the $(Password) used to configure local SQL Server
  # instances.  In such a case, we must generate a random password and clobber $(Password).
  #
  # From this point forward in this stage, any pipeline runtime expansion of $(Password) will use
  # the random value.  This includes the SQL Server config templates (configure-sql-server-*.yml),
  # and the expansion of connection strings via our configProperties parameter.
  #
  # Azure Pipelines provides the System.PullRequest.IsFork variable that is available at template
  # expansion time.  See:
  #
  #  https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#system-variables
  #
  - ${{ if eq(variables['System.PullRequest.IsFork'], 'true') }}:
    - pwsh: |
        $guid = [guid]::NewGuid().ToString()
        Write-Host "##vso[task.setvariable variable=Password;isSecret=true]$guid"
      displayName: Generate random SQL Server password for forked repo

  - ${{ if ne(parameters.configProperties, '{}') }}:
    - template: /eng/pipelines/common/templates/steps/update-config-file-step.yml@self # update config.json file
      parameters:
        debug: ${{ parameters.debug }}
        UseManagedSNIOnWindows: ${{ parameters.usemanagedSNI }}
        ${{ if parameters.configProperties.TCPConnectionString }}:
          TCPConnectionString: ${{ parameters.configProperties.TCPConnectionString }}
        ${{ if parameters.configProperties.NPConnectionString }}:
          NPConnectionString: ${{ parameters.configProperties.NPConnectionString }}
        ${{ if parameters.configProperties.AADAuthorityURL }}:
          AADAuthorityURL: ${{ parameters.configProperties.AADAuthorityURL }}
        ${{ if parameters.configProperties.TCPConnectionStringHGSVBS }}:
          TCPConnectionStringHGSVBS: ${{ parameters.configProperties.TCPConnectionStringHGSVBS }}
        ${{ if parameters.configProperties.TCPConnectionStringNoneVBS }}:
          TCPConnectionStringNoneVBS: ${{ parameters.configProperties.TCPConnectionStringNoneVBS }}
        ${{ if parameters.configProperties.TCPConnectionStringAASSGX }}:
          TCPConnectionStringAASSGX: ${{ parameters.configProperties.TCPConnectionStringAASSGX }}
        ${{ if parameters.configProperties.EnclaveEnabled }}:
          EnclaveEnabled: ${{ eq(parameters.configProperties.EnclaveEnabled, 'true') }}
        ${{ if parameters.configProperties.TracingEnabled }}:
          TracingEnabled: ${{ eq(parameters.configProperties.TracingEnabled, 'true') }}
        ${{ if parameters.configProperties.AADPasswordConnectionString }}:
          AADPasswordConnectionString: ${{ parameters.configProperties.AADPasswordConnectionString }}
        ${{ if parameters.configProperties.AADServicePrincipalId }}:
          AADServicePrincipalId: ${{ parameters.configProperties.AADServicePrincipalId }}
        ${{ if parameters.configProperties.AADServicePrincipalSecret }}:
          AADServicePrincipalSecret: ${{ parameters.configProperties.AADServicePrincipalSecret }}
        ${{ if parameters.configProperties.AzureKeyVaultUrl }}:
          AzureKeyVaultUrl: ${{ parameters.configProperties.AzureKeyVaultUrl }}
        ${{ if parameters.configProperties.AzureKeyVaultTenantId }}:
          AzureKeyVaultTenantId: ${{ parameters.configProperties.AzureKeyVaultTenantId }}
        ${{ if parameters.configProperties.UserManagedIdentityClientId }}:
          UserManagedIdentityClientId: ${{ parameters.configProperties.UserManagedIdentityClientId }}
        ${{ if parameters.configProperties.FileStreamDirectory }}:
          FileStreamDirectory: ${{ parameters.configProperties.FileStreamDirectory }}
        ${{ if parameters.configProperties.LocalDbAppName }}:
          LocalDbAppName: ${{ parameters.configProperties.LocalDbAppName }}
        ${{ if parameters.configProperties.LocalDbSharedInstanceName }}:
          LocalDbSharedInstanceName: ${{ parameters.configProperties.LocalDbSharedInstanceName }}
        ${{ if parameters.configProperties.AliasName }}:
          AliasName: ${{ parameters.configProperties.AliasName }}
        ${{ if parameters.configProperties.SupportsIntegratedSecurity }}:
          SupportsIntegratedSecurity: ${{ eq(parameters.configProperties.SupportsIntegratedSecurity, 'true') }}
        ${{ if parameters.configProperties.SupportsFileStream }}:
          SupportsFileStream: ${{ eq(parameters.configProperties.SupportsFileStream, 'true') }}
        ${{ if parameters.configProperties.DNSCachingConnString }}:
          DNSCachingConnString: ${{ parameters.configProperties.DNSCachingConnString }}
        ${{ if parameters.configProperties.DNSCachingServerCR }}:
          DNSCachingServerCR: ${{ parameters.configProperties.DNSCachingServerCR }}
        ${{ if parameters.configProperties.DNSCachingServerTR }}:
          DNSCachingServerTR: ${{ parameters.configProperties.DNSCachingServerTR }}
        ${{ if parameters.configProperties.EnclaveAzureDatabaseConnString }}:
          EnclaveAzureDatabaseConnString: ${{ parameters.configProperties.EnclaveAzureDatabaseConnString }}
        ${{ if parameters.configProperties.IsDNSCachingSupportedCR }}:
          IsDNSCachingSupportedCR: ${{ eq(parameters.configProperties.IsDNSCachingSupportedCR, 'true') }}
        ${{ if parameters.configProperties.IsDNSCachingSupportedTR }}:
          IsDNSCachingSupportedTR: ${{ eq(parameters.configProperties.IsDNSCachingSupportedTR, 'true') }}
        ${{ if parameters.configProperties.IsAzureSynapse }}:
          IsAzureSynapse: ${{ eq(parameters.configProperties.IsAzureSynapse, 'true') }}
        ${{ if parameters.configProperties.ManagedIdentitySupported }}:
          ManagedIdentitySupported: ${{ eq(parameters.configProperties.ManagedIdentitySupported, 'true') }}

    - ${{ if and(eq(parameters.configSqlFor, 'azure'), eq(parameters.operatingSystem, 'Windows')) }}:
      - powershell: |
          # Try to start the SQL Browser service, if it exists
          $svc_name = "SQLBrowser"
          if ((Get-Service -Name "$svc_name" -ErrorAction SilentlyContinue) -ne $null) {
              Get-Service $svc_name | Select-Object -Property Name, StartType, Status
              Set-Service -StartupType Automatic $svc_name
              net start $svc_name
              Get-Service $svc_name | Select-Object -Property Name, StartType, Status
          }

        displayName: 'Start Sql Browser'
        condition: eq(variables['Agent.OS'], 'Windows_NT')
    - ${{ elseif eq(parameters.configSqlFor, 'local') }}:
      - template: /eng/pipelines/common/templates/steps/configure-sql-server-step.yml@self # configure SQL Server
        parameters:
          operatingSystem: ${{ parameters.operatingSystem }}
          netcoreVersionTestUtils: ${{ parameters.netcoreVersionTestUtils }}
          ${{ if parameters.configProperties.instanceName }}:
            instanceName: ${{ parameters.configProperties.instanceName }}
          ${{ if parameters.configProperties.user }}:
            user: ${{ parameters.configProperties.user }}
          ${{ if parameters.configProperties.saUser }}:
            saUser: ${{ parameters.configProperties.saUser }}
          ${{ if parameters.configProperties.SQLRootPath }}:
            SQLRootPath: ${{ parameters.configProperties.SQLRootPath }}
          ${{ if parameters.configProperties.x64AliasRegistryPath }}:
            x64AliasRegistryPath: ${{ parameters.configProperties.x64AliasRegistryPath }}
          ${{ if parameters.configProperties.x86AliasRegistryPath }}:
            x86AliasRegistryPath: ${{ parameters.configProperties.x86AliasRegistryPath }}
          ${{ if parameters.configProperties.SQLAliasName }}:
            SQLAliasName: ${{ parameters.configProperties.SQLAliasName }}
          ${{ if parameters.configProperties.SQLAliasPort }}:
            SQLAliasPort: ${{ parameters.configProperties.SQLAliasPort }}
          ${{ if parameters.configProperties.databaseName }}:
            databaseName: ${{ parameters.configProperties.databaseName }}
          ${{ if parameters.configProperties.enableLocalDB }}:
            enableLocalDB: ${{ parameters.configProperties.enableLocalDB }}
          ${{ if parameters.configProperties.localDbAppName }}:
            LocalDbAppName: ${{ parameters.configProperties.localDbAppName }}
          ${{ if parameters.configProperties.localDbSharedInstanceName }}:
            LocalDbSharedInstanceName: ${{ parameters.configProperties.localDbSharedInstanceName }}
          ${{ if parameters.configProperties.FileStreamDirectory }}:
            fileStreamDirectory: ${{ parameters.configProperties.FileStreamDirectory }}

    - template: /eng/pipelines/common/templates/steps/build-all-tests-step.yml@self # build tests
      parameters:
        targetFramework: ${{ parameters.targetFramework }}
        buildConfiguration: ${{ parameters.buildConfiguration }}
        referenceType: ${{ parameters.referenceType }}
        testSet: ${{ parameters.testSet }}
        abstractionsPackageVersion: ${{ parameters.abstractionsPackageVersion }}
        mdsPackageVersion: ${{ parameters.mdsPackageVersion }}
        ${{ if ne(parameters.operatingSystem, 'Windows') }}:
          OSGroup: Unix

  - ${{ if eq(parameters.enableX64Test, true) }}: # run native tests
    - template: /eng/pipelines/common/templates/steps/run-all-tests-step.yml@self # run tests
      parameters:
        debug: ${{ parameters.debug }}
        targetFramework: ${{ parameters.targetFramework }}
        buildConfiguration: ${{ parameters.buildConfiguration }}
        referenceType: ${{ parameters.referenceType }}
        testSet: ${{ parameters.testSet }}
        operatingSystem: ${{ parameters.operatingSystem }}
        abstractionsPackageVersion: ${{ parameters.abstractionsPackageVersion }}
        mdsPackageVersion: ${{ parameters.mdsPackageVersion }}

  - ${{ if and(eq(parameters.enableX86Test, true), eq(parameters.operatingSystem, 'Windows')) }}:
    # Set up for x86 tests by manually installing dotnet for x86 to an alternative location. This
    # is only used to execute the test runtime (framework to test is specified in build params), so
    # it should be acceptable to just install a specific version in all cases.
    # @TODO: This setup is very confusing. Ideally we should just be utilizing the dotnet installation
    #    earlier in the job. There has to be a cleaner way of doing this.
    - ${{ if ne(variables['dotnetx86RootPath'], '') }}:
      # Install the .NET SDK and Runtimes for x86.
      - template: /eng/pipelines/steps/install-dotnet.yml@self
        parameters:
          architecture: x86
          debug: ${{ parameters.debug }}
          installDir: $(dotnetx86RootPath)
          runtimes: [8.x, 9.x]

    - template: /eng/pipelines/common/templates/steps/run-all-tests-step.yml@self
      parameters:
        debug: ${{ parameters.debug }}
        targetFramework: ${{ parameters.targetFramework }}
        buildConfiguration: ${{ parameters.buildConfiguration }}
        referenceType: ${{ parameters.referenceType }}
        testSet: ${{ parameters.testSet }}
        msbuildArchitecture: x86
        dotnetx86RootPath: $(dotnetx86RootPath)
        operatingSystem: ${{ parameters.operatingSystem }}
        abstractionsPackageVersion: ${{ parameters.abstractionsPackageVersion }}
        mdsPackageVersion: ${{ parameters.mdsPackageVersion }}

  - ${{ if eq(parameters.publishTestResults, true) }}:
    - template: /eng/pipelines/common/templates/steps/publish-test-results-step.yml@self
      parameters:
        debug: ${{ parameters.debug }}
        targetFramework: ${{ parameters.targetFramework }}
        operatingSystem: ${{ parameters.operatingSystem }}
        buildConfiguration: ${{ parameters.buildConfiguration }}
