#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################
parameters:
  - name: downloadPackageStep
    type: step
    default:
      script: echo <empty step>

  - name: dependsOn
    type: string
    default: empty

  - name: isPreview
    type: boolean

  # The timeout, in minutes, for this job.
  - name: timeout
    type: number

jobs:
- job: run_tests_package_reference
  displayName: 'Run tests with package reference'
  ${{ if ne(parameters.dependsOn, 'empty')}}:
    dependsOn: '${{parameters.dependsOn }}'

  # Some of our tests take longer than the default 60 minutes to run on some
  # OSes and configurations.
  timeoutInMinutes: ${{ parameters.timeout }}

  pool:
    type: windows  # read more about custom job pool types at https://aka.ms/obpipelines/yaml/jobs
    isCustom: true
    name: ADO-1ES-Pool
    vmImage: 'ADO-MMS22-SQL19'

  variables: # More settings at https://aka.ms/obpipelines/yaml/jobs
  - template: /eng/pipelines/libraries/mds-validation-variables.yml@self

  steps:
  - template: /eng/pipelines/common/templates/steps/pre-build-step.yml

  - ${{parameters.downloadPackageStep }}

  - template: /eng/pipelines/common/templates/steps/update-config-file-step.yml
    parameters:
      # We use the Library $(Password) variable as the SA password in this pipeline.
      saPassword: $(Password)
      TCPConnectionString: $(SQL_TCP_CONN_STRING)
      NPConnectionString: $(SQL_NP_CONN_STRING)
      SupportsIntegratedSecurity: false

  - template: /eng/pipelines/common/templates/steps/prepare-test-db-step.yml

# build & test
  - template: /eng/pipelines/common/templates/steps/build-and-run-tests-netfx-step.yml
    parameters:
      ${{ if parameters.isPreview }}:
        abstractionsPackageVersion: $(abstractionsPackagePreviewVersion)
        mdsPackageVersion: $(previewMdsPackageVersion)

  - template: /eng/pipelines/common/templates/steps/build-and-run-tests-netcore-step.yml
    parameters:
      ${{ if parameters.isPreview }}:
        abstractionsPackageVersion: $(abstractionsPackagePreviewVersion)
        mdsPackageVersion: $(previewMdsPackageVersion)
