
Starting test 'SqlVariantParam'
SendVariantBulkCopy[SqlDataReader]       -> System.Data.SqlTypes.SqlSingle:real
SendVariantBulkCopy[DataTable]           -> System.Data.SqlTypes.SqlSingle:real
SendVariantBulkCopy[DataRow]             -> System.Data.SqlTypes.SqlSingle:real
SendVariantParam                         -> System.Data.SqlTypes.SqlSingle:real
SendVariantTvp[SqlMetaData]              -> System.Data.SqlTypes.SqlSingle:real
SendVariantTvp[SqlDataReader]            -> System.Data.SqlTypes.SqlSingle:real
SendVariantBulkCopy[SqlDataReader]       -> System.Data.SqlTypes.SqlSingle:real
SendVariantBulkCopy[DataTable]           -> System.Data.SqlTypes.SqlSingle:real
SendVariantBulkCopy[DataRow]             -> System.Data.SqlTypes.SqlSingle:real
SendVariantParam                         -> System.Data.SqlTypes.SqlSingle:real
SendVariantTvp[SqlMetaData]              -> System.Data.SqlTypes.SqlSingle:real
SendVariantTvp[SqlDataReader]            -> System.Data.SqlTypes.SqlSingle:real
SendVariantBulkCopy[SqlDataReader]       -> System.Data.SqlTypes.SqlString:nvarchar
SendVariantBulkCopy[DataTable]           -> System.Data.SqlTypes.SqlString:nvarchar
SendVariantBulkCopy[DataRow]             -> System.Data.SqlTypes.SqlString:nvarchar
SendVariantParam                         -> System.Data.SqlTypes.SqlString:nvarchar
SendVariantTvp[SqlMetaData]              -> System.Data.SqlTypes.SqlString:nvarchar
SendVariantTvp[SqlDataReader]            -> System.Data.SqlTypes.SqlString:nvarchar
SendVariantBulkCopy[SqlDataReader]       -> System.Data.SqlTypes.SqlDouble:float
SendVariantBulkCopy[DataTable]           -> System.Data.SqlTypes.SqlDouble:float
SendVariantBulkCopy[DataRow]             -> System.Data.SqlTypes.SqlDouble:float
SendVariantParam                         -> System.Data.SqlTypes.SqlDouble:float
SendVariantTvp[SqlMetaData]              -> System.Data.SqlTypes.SqlDouble:float
SendVariantTvp[SqlDataReader]            -> System.Data.SqlTypes.SqlDouble:float
SendVariantBulkCopy[SqlDataReader]       -> System.Data.SqlTypes.SqlBinary:varbinary
SendVariantBulkCopy[DataTable]           -> System.Data.SqlTypes.SqlBinary:varbinary
SendVariantBulkCopy[DataRow]             -> System.Data.SqlTypes.SqlBinary:varbinary
SendVariantParam                         -> System.Data.SqlTypes.SqlBinary:varbinary
SendVariantTvp[SqlMetaData]              -> System.Data.SqlTypes.SqlBinary:varbinary
SendVariantTvp[SqlDataReader]            -> System.Data.SqlTypes.SqlBinary:varbinary
SendVariantBulkCopy[SqlDataReader]       -> System.Data.SqlTypes.SqlGuid:uniqueidentifier
SendVariantBulkCopy[DataTable]           -> System.Data.SqlTypes.SqlGuid:uniqueidentifier
SendVariantBulkCopy[DataRow]             -> System.Data.SqlTypes.SqlGuid:uniqueidentifier
SendVariantParam                         -> System.Data.SqlTypes.SqlGuid:uniqueidentifier
SendVariantTvp[SqlMetaData]              -> System.Data.SqlTypes.SqlGuid:uniqueidentifier
SendVariantTvp[SqlDataReader]            -> System.Data.SqlTypes.SqlGuid:uniqueidentifier
SendVariantBulkCopy[SqlDataReader]       -> System.Data.SqlTypes.SqlBoolean:bit
SendVariantBulkCopy[DataTable]           -> System.Data.SqlTypes.SqlBoolean:bit
SendVariantBulkCopy[DataRow]             -> System.Data.SqlTypes.SqlBoolean:bit
SendVariantParam                         -> System.Data.SqlTypes.SqlBoolean:bit
SendVariantTvp[SqlMetaData]              -> System.Data.SqlTypes.SqlBoolean:bit
SendVariantTvp[SqlDataReader]            -> System.Data.SqlTypes.SqlBoolean:bit
SendVariantBulkCopy[SqlDataReader]       -> System.Data.SqlTypes.SqlBoolean:bit
SendVariantBulkCopy[DataTable]           -> System.Data.SqlTypes.SqlBoolean:bit
SendVariantBulkCopy[DataRow]             -> System.Data.SqlTypes.SqlBoolean:bit
SendVariantParam                         -> System.Data.SqlTypes.SqlBoolean:bit
SendVariantTvp[SqlMetaData]              -> System.Data.SqlTypes.SqlBoolean:bit
SendVariantTvp[SqlDataReader]            -> System.Data.SqlTypes.SqlBoolean:bit
SendVariantBulkCopy[SqlDataReader]       -> System.Data.SqlTypes.SqlByte:tinyint
SendVariantBulkCopy[DataTable]           -> System.Data.SqlTypes.SqlByte:tinyint
SendVariantBulkCopy[DataRow]             -> System.Data.SqlTypes.SqlByte:tinyint
SendVariantParam                         -> System.Data.SqlTypes.SqlByte:tinyint
SendVariantTvp[SqlMetaData]              -> System.Data.SqlTypes.SqlByte:tinyint
SendVariantTvp[SqlDataReader]            -> System.Data.SqlTypes.SqlByte:tinyint
SendVariantBulkCopy[SqlDataReader]       -> System.Data.SqlTypes.SqlInt16:smallint
SendVariantBulkCopy[DataTable]           -> System.Data.SqlTypes.SqlInt16:smallint
SendVariantBulkCopy[DataRow]             -> System.Data.SqlTypes.SqlInt16:smallint
SendVariantParam                         -> System.Data.SqlTypes.SqlInt16:smallint
SendVariantTvp[SqlMetaData]              -> System.Data.SqlTypes.SqlInt16:smallint
SendVariantTvp[SqlDataReader]            -> System.Data.SqlTypes.SqlInt16:smallint
SendVariantBulkCopy[SqlDataReader]       -> System.Data.SqlTypes.SqlInt32:int
SendVariantBulkCopy[DataTable]           -> System.Data.SqlTypes.SqlInt32:int
SendVariantBulkCopy[DataRow]             -> System.Data.SqlTypes.SqlInt32:int
SendVariantParam                         -> System.Data.SqlTypes.SqlInt32:int
SendVariantTvp[SqlMetaData]              -> System.Data.SqlTypes.SqlInt32:int
SendVariantTvp[SqlDataReader]            -> System.Data.SqlTypes.SqlInt32:int
SendVariantBulkCopy[SqlDataReader]       -> System.Data.SqlTypes.SqlInt64:bigint
SendVariantBulkCopy[DataTable]           -> System.Data.SqlTypes.SqlInt64:bigint
SendVariantBulkCopy[DataRow]             -> System.Data.SqlTypes.SqlInt64:bigint
SendVariantParam                         -> System.Data.SqlTypes.SqlInt64:bigint
SendVariantTvp[SqlMetaData]              -> System.Data.SqlTypes.SqlInt64:bigint
SendVariantTvp[SqlDataReader]            -> System.Data.SqlTypes.SqlInt64:bigint
SendVariantBulkCopy[SqlDataReader]       -> System.Data.SqlTypes.SqlDecimal:numeric
SendVariantBulkCopy[DataTable]           -> System.Data.SqlTypes.SqlDecimal:numeric
SendVariantBulkCopy[DataRow]             -> System.Data.SqlTypes.SqlDecimal:numeric
SendVariantParam                         -> System.Data.SqlTypes.SqlDecimal:numeric
SendVariantTvp[SqlMetaData]              -> System.Data.SqlTypes.SqlDecimal:numeric
SendVariantTvp[SqlDataReader]            -> System.Data.SqlTypes.SqlDecimal:numeric
SendVariantBulkCopy[SqlDataReader]       -> System.Data.SqlTypes.SqlDateTime:datetime
SendVariantBulkCopy[DataTable]           -> System.Data.SqlTypes.SqlDateTime:datetime
SendVariantBulkCopy[DataRow]             -> System.Data.SqlTypes.SqlDateTime:datetime
SendVariantParam                         -> System.Data.SqlTypes.SqlDateTime:datetime
SendVariantTvp[SqlMetaData]              -> System.Data.SqlTypes.SqlDateTime:datetime
SendVariantTvp[SqlDataReader]            -> System.Data.SqlTypes.SqlDateTime:datetime
SendVariantBulkCopy[SqlDataReader]       -> System.Data.SqlTypes.SqlDecimal:numeric
   --> ERROR: Expected type System.Data.SqlTypes.SqlMoney does not match actual type System.Data.SqlTypes.SqlDecimal
   --> ERROR: Expected base type money does not match actual base type numeric
SendVariantBulkCopy[DataTable]           -> System.Data.SqlTypes.SqlDecimal:numeric
   --> ERROR: Expected type System.Data.SqlTypes.SqlMoney does not match actual type System.Data.SqlTypes.SqlDecimal
   --> ERROR: Expected base type money does not match actual base type numeric
SendVariantBulkCopy[DataRow]             -> System.Data.SqlTypes.SqlDecimal:numeric
   --> ERROR: Expected type System.Data.SqlTypes.SqlMoney does not match actual type System.Data.SqlTypes.SqlDecimal
   --> ERROR: Expected base type money does not match actual base type numeric
SendVariantParam                         -> System.Data.SqlTypes.SqlMoney:money
SendVariantTvp[SqlMetaData]              -> System.Data.SqlTypes.SqlMoney:money
SendVariantTvp[SqlDataReader]            -> System.Data.SqlTypes.SqlMoney:money
End test 'SqlVariantParam'
