// Do not edit this file manually it is auto-generated during the build based on the .resx file for this project.

namespace System
{

    internal static partial class SR
    {
        internal static System.Type ResourceType { get; } = typeof(Strings); 
    }
}
