-- Licensed to the .NET Foundation under one or more agreements.
-- The .NET Foundation licenses this file to you under the MIT license.
-- See the LICENSE file in the project root for more information.
--
-- dropOrphanedAlwaysEncryptedKeys.sql
--
-- PURPOSE
--   Removes leftover Always Encrypted (AE) test artifacts from a database so
--   that CREATE COLUMN ENCRYPTION KEY / CREATE COLUMN MASTER KEY stop failing
--   with:
--
--       Msg ... : Create failed because all available identifiers have been
--                 exhausted.
--
--   SQL Server assigns every Column Master Key (CMK) and Column Encryption Key
--   (CEK) an identifier drawn from a bounded range. When AE test runs are
--   cancelled, time out, or fail mid-setup, their keys are never dropped and
--   accumulate on long-lived shared servers (e.g. the Kerberos CI instance
--   sqldrv-sql22). Once the CEK id range fills up, every subsequent create
--   fails. This script drops the leaked keys (and the tables that depend on
--   them) to free the id space.
--
-- SCOPE / SAFETY
--   Only objects generated by the AE manual-test fixtures are touched. Those
--   fixtures name every object with a well-known prefix:
--       DatabaseHelper.GenerateUniqueName  -> "AE_<name>_<guid>"
--       SQLSetupStrategy.GenerateUniqueName -> "AE-<name>-<guid>"
--   So this script only removes CMKs, CEKs, and tables whose names begin with
--   'AE_' or 'AE-'. Non-test objects are left untouched.
--
-- USAGE
--   1. Connect to the target database (AE keys are per-database):
--          sqlcmd -S <server> -d <database> -i dropOrphanedAlwaysEncryptedKeys.sql
--      or add a USE [<database>] statement below.
--   2. Preview first: leave @WhatIf = 1 to print the DROP statements only.
--   3. To actually delete, set @WhatIf = 0 and re-run.
--
-- Drop order (dependency-driven):
--   1. Tables with encrypted columns that reference a leaked CEK.
--   2. The leaked CEKs.
--   3. The leaked CMKs.

SET NOCOUNT ON;

-------------------------------------------------------------------------------
-- Configuration
-------------------------------------------------------------------------------
DECLARE @WhatIf bit = 1;   -- 1 = preview (print only), 0 = execute the drops

-------------------------------------------------------------------------------
-- Working variables
-------------------------------------------------------------------------------
DECLARE @stmt   nvarchar(max);
DECLARE @label  nvarchar(400);
DECLARE @errMsg nvarchar(4000);
DECLARE @tables int = 0, @ceks int = 0, @cmks int = 0;
DECLARE @failures int = 0;

PRINT '=== Always Encrypted orphaned-key cleanup on database [' + DB_NAME() + '] ===';
PRINT CASE WHEN @WhatIf = 1
           THEN 'MODE: preview (set @WhatIf = 0 to execute)'
           ELSE 'MODE: EXECUTE' END;
PRINT '';

-------------------------------------------------------------------------------
-- Step 1: Tables whose encrypted columns depend on a leaked (AE-prefixed) CEK.
--         These must be dropped before their CEKs can be removed.
-------------------------------------------------------------------------------
DECLARE @dropTables TABLE (seq int IDENTITY(1,1) PRIMARY KEY, tableName nvarchar(517));

INSERT INTO @dropTables (tableName)
SELECT DISTINCT QUOTENAME(SCHEMA_NAME(t.schema_id)) + N'.' + QUOTENAME(t.name)
FROM sys.columns AS c
JOIN sys.tables  AS t   ON t.object_id = c.object_id
JOIN sys.column_encryption_keys AS cek
     ON cek.column_encryption_key_id = c.column_encryption_key_id
WHERE c.column_encryption_key_id <> 0
  AND (cek.name LIKE 'AE[_]%' OR cek.name LIKE 'AE-%')
UNION
-- Also catch AE-prefixed tables directly, even if their columns are not
-- currently mapped to a surviving CEK.
SELECT QUOTENAME(SCHEMA_NAME(t.schema_id)) + N'.' + QUOTENAME(t.name)
FROM sys.tables AS t
WHERE t.name LIKE 'AE[_]%' OR t.name LIKE 'AE-%';

PRINT '--- Step 1: dependent / AE-prefixed tables ---';
DECLARE @i int = 1, @n int = (SELECT COUNT(*) FROM @dropTables);
WHILE @i <= @n
BEGIN
    SELECT @label = tableName FROM @dropTables WHERE seq = @i;
    SET @stmt = N'DROP TABLE ' + @label + N';';
    IF @WhatIf = 1
        PRINT @stmt;
    ELSE
    BEGIN
        BEGIN TRY
            EXEC sp_executesql @stmt;
            SET @tables += 1;
            PRINT 'Dropped table ' + @label;
        END TRY
        BEGIN CATCH
            SET @failures += 1;
            SET @errMsg = ERROR_MESSAGE();
            PRINT 'FAILED to drop table ' + @label + ': ' + @errMsg;
        END CATCH
    END
    SET @i += 1;
END
IF @n = 0 PRINT '(none)';
PRINT '';

-------------------------------------------------------------------------------
-- Step 2: Leaked Column Encryption Keys.
-------------------------------------------------------------------------------
DECLARE @dropCeks TABLE (seq int IDENTITY(1,1) PRIMARY KEY, keyName nvarchar(258));

INSERT INTO @dropCeks (keyName)
SELECT QUOTENAME(name)
FROM sys.column_encryption_keys
WHERE name LIKE 'AE[_]%' OR name LIKE 'AE-%';

PRINT '--- Step 2: column encryption keys ---';
SET @i = 1; SET @n = (SELECT COUNT(*) FROM @dropCeks);
WHILE @i <= @n
BEGIN
    SELECT @label = keyName FROM @dropCeks WHERE seq = @i;
    SET @stmt = N'DROP COLUMN ENCRYPTION KEY ' + @label + N';';
    IF @WhatIf = 1
        PRINT @stmt;
    ELSE
    BEGIN
        BEGIN TRY
            EXEC sp_executesql @stmt;
            SET @ceks += 1;
            PRINT 'Dropped CEK ' + @label;
        END TRY
        BEGIN CATCH
            SET @failures += 1;
            SET @errMsg = ERROR_MESSAGE();
            PRINT 'FAILED to drop CEK ' + @label + ': ' + @errMsg;
        END CATCH
    END
    SET @i += 1;
END
IF @n = 0 PRINT '(none)';
PRINT '';

-------------------------------------------------------------------------------
-- Step 3: Leaked Column Master Keys.
-------------------------------------------------------------------------------
DECLARE @dropCmks TABLE (seq int IDENTITY(1,1) PRIMARY KEY, keyName nvarchar(258));

INSERT INTO @dropCmks (keyName)
SELECT QUOTENAME(name)
FROM sys.column_master_keys
WHERE name LIKE 'AE[_]%' OR name LIKE 'AE-%';

PRINT '--- Step 3: column master keys ---';
SET @i = 1; SET @n = (SELECT COUNT(*) FROM @dropCmks);
WHILE @i <= @n
BEGIN
    SELECT @label = keyName FROM @dropCmks WHERE seq = @i;
    SET @stmt = N'DROP COLUMN MASTER KEY ' + @label + N';';
    IF @WhatIf = 1
        PRINT @stmt;
    ELSE
    BEGIN
        BEGIN TRY
            EXEC sp_executesql @stmt;
            SET @cmks += 1;
            PRINT 'Dropped CMK ' + @label;
        END TRY
        BEGIN CATCH
            SET @failures += 1;
            SET @errMsg = ERROR_MESSAGE();
            PRINT 'FAILED to drop CMK ' + @label + ': ' + @errMsg;
        END CATCH
    END
    SET @i += 1;
END
IF @n = 0 PRINT '(none)';
PRINT '';

-------------------------------------------------------------------------------
-- Summary
-------------------------------------------------------------------------------
PRINT '=== Summary ===';
IF @WhatIf = 1
BEGIN
    DECLARE @candTables int = (SELECT COUNT(*) FROM @dropTables);
    DECLARE @candCeks   int = (SELECT COUNT(*) FROM @dropCeks);
    DECLARE @candCmks   int = (SELECT COUNT(*) FROM @dropCmks);
    PRINT 'Preview only. Candidate tables: '
        + CAST(@candTables AS nvarchar(10))
        + ', CEKs: ' + CAST(@candCeks AS nvarchar(10))
        + ', CMKs: ' + CAST(@candCmks AS nvarchar(10)) + '.';
    PRINT 'Set @WhatIf = 0 and re-run to execute.';
END
ELSE
BEGIN
    PRINT 'Dropped tables: ' + CAST(@tables AS nvarchar(10))
        + ', CEKs: ' + CAST(@ceks AS nvarchar(10))
        + ', CMKs: ' + CAST(@cmks AS nvarchar(10))
        + ', failures: ' + CAST(@failures AS nvarchar(10)) + '.';

    -- Report remaining AE-prefixed keys, if any (e.g. still-referenced CEKs).
    IF EXISTS (SELECT 1 FROM sys.column_encryption_keys WHERE name LIKE 'AE[_]%' OR name LIKE 'AE-%')
        OR EXISTS (SELECT 1 FROM sys.column_master_keys WHERE name LIKE 'AE[_]%' OR name LIKE 'AE-%')
    BEGIN
        PRINT '';
        PRINT 'WARNING: some AE-prefixed keys remain (likely still referenced by a table):';
        SELECT 'CEK' AS keyType, name FROM sys.column_encryption_keys
        WHERE name LIKE 'AE[_]%' OR name LIKE 'AE-%'
        UNION ALL
        SELECT 'CMK', name FROM sys.column_master_keys
        WHERE name LIKE 'AE[_]%' OR name LIKE 'AE-%';
    END
END
GO
