#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################

name: $(Year:YY)$(DayOfYear)$(Rev:.rr)

# 5.1 was retired on 20 Jan 2026.
pr: none
trigger: none

parameters: # parameters are shown up in ADO UI in a build queue time
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

- name: publishSymbols
  type: boolean
  default: false

# GOTCHA: This must be a previously published MDS package version.  This
# pipeline isn't capable of using the MDS package being built as input for
# the AKV package build.
- name: MDS_PackageRef_Version
  displayName: 'Publicly available MDS package version for AKV Provider build'
  type: string
  default: 5.1.7

- name: CurrentNetFxVersion
  displayName: 'Lowest supported .NET Framework version (MDS validation)'
  type: string
  default: 'net462'

- name: enableAllSdlTools
  displayName: 'Enable all SDL tools'
  type: boolean
  default: true

- name: oneBranchType
  displayName: 'Select OneBranch template'
  default: Official
  values:
  - NonOfficial
  - Official

# The timeout, in minutes, for each test job.
- name: testsTimeout
  displayName: 'Tests timeout (in minutes)'
  type: string
  default: 90

variables:
  - template: /eng/pipelines/libraries/variables.yml@self
  - name: packageFolderName
    value: drop_buildMDS_build_signed_package
  - name: PublishSymbols
    value: ${{ parameters['publishSymbols'] }}
  - name: CurrentNetFxVersion
    value: ${{ parameters['CurrentNetFxVersion'] }}
  - name: ProductVersion    #MDS product version (MDS validation)
    value: $(NUGETPACKAGEVERSION)

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.${{parameters.oneBranchType }}.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    featureFlags:
      WindowsHostVersion: 1ESWindows2022
    globalSdl: # https://aka.ms/obpipelines/sdl
      tsa:
        # The OneBranch template will set 'break' to false for the other SDL
        # tools when TSA is enabled.  This allows TSA to gather the results
        # and publish them for downstream analysis.
        enabled: ${{parameters.enableAllSdlTools }}
      apiscan:
        enabled: ${{parameters.enableAllSdlTools }}
        # For non-official builds, the OneBranch template seems to set APIScan's
        # 'break' to true even when TSA is enabled.  We don't want APIScan to
        # break non-official builds, so we explicitly set 'break' to false here.
        ${{ if ne(parameters.oneBranchType, 'Official') }}:
          break: false
        softwareFolder: $(softwareFolder)
        symbolsFolder: $(symbolsFolder)
        softwarename: Microsoft.Data.SqlClient
        versionNumber: $(AssemblyFileVersion)
      codeql:
        compiled:
          enabled: false #[warning]Consider running CodeQL on the default branch only.
      sbom:
        enabled: ${{parameters.enableAllSdlTools }}
        packageName: Microsoft.Data.SqlClient
        packageVersion: $(NugetPackageVersion)
      policheck:
        enabled: ${{parameters.enableAllSdlTools }}
        break: true # always break the build on policheck issues. You can disable it by setting to 'false'
        exclusionsFile: $(REPOROOT)\.config\PolicheckExclusions.xml
      asyncSdl:
        enabled: false
        credscan:
          enabled: ${{parameters.enableAllSdlTools }}
          suppressionsFile: $(REPOROOT)/.config/CredScanSuppressions.json
        binskim:
          enabled: ${{parameters.enableAllSdlTools }}
        armory:
          enabled: ${{parameters.enableAllSdlTools }}
          break: true
        eslint: # TypeScript and JavaScript
          enabled: false
        roslyn:
          enabled: ${{parameters.enableAllSdlTools }}
          break: true
        publishLogs:
          enabled: ${{parameters.enableAllSdlTools }}
        tsaOptionsPath: $(REPOROOT)\.config\tsaoptions.json
        disableLegacyManifest: true
    stages:
    - stage: buildMDS
      displayName: 'Build MDS'
      jobs:
      - template: eng/pipelines/common/templates/jobs/build-signed-package-job.yml@self
        parameters:
          symbolsFolder: $(symbolsFolder)
          softwareFolder: $(softwareFolder)
          publishSymbols: ${{ parameters['publishSymbols'] }}

    - stage: buildAKV
      displayName: 'Build AKV Provider'
      jobs:
      - template: eng/pipelines/common/templates/jobs/build-signed-akv-package-job.yml@self
        parameters:
          symbolsFolder: $(symbolsFolder)
          softwareFolder: $(softwareFolder)
          mdsPackageVersion: ${{ parameters['MDS_PackageRef_Version'] }}
          publishSymbols: ${{ parameters['publishSymbols'] }}

    - stage: mds_package_validation
      displayName: 'MDS Package Validation'
      dependsOn: buildMDS
      jobs:
      - template: eng/pipelines/common/templates/jobs/validate-signed-package-job.yml@self
        parameters:
          packageFolderName: $(packageFolderName)
          downloadPackageStep:
            download: current
            artifact: $(packageFolderName)
            patterns: '**/*.nupkg'
            displayName: 'Download NuGet Package'

      - template: eng/pipelines/common/templates/jobs/run-tests-package-reference-job.yml@self
        parameters:
          packageFolderName: $(packageFolderName)
          timeout: ${{ parameters.testsTimeout }}
          downloadPackageStep:
            download: current
            artifact: $(packageFolderName)
            patterns: '**/*.nupkg'
            displayName: 'Download NuGet Package'
