#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################

name: $(Year:YY)$(DayOfYear)$(Rev:.r)
trigger:
  branches:
    include:

    # This pipeline is intended to only run against the ADO.Net dotnet-sqlclient
    # repo.
    - internal/main
  paths:
    include:
    - .azuredevops
    - .config
    - doc
    - eng/pipelines
    - src
    - tools
    - azurepipelines-coverage.yml
    - build.proj
    - NuGet.config

schedules:
- cron: '30 4 * * Mon'
  displayName: Weekly Sunday 9:30 PM (UTC - 7) Build
  branches:
    include:
    - internal/main
  always: true

- cron: '30 3 * * Mon-Fri'
  displayName: Mon-Fri 8:30 PM (UTC - 7) Build
  branches:
    include:
    - internal/main

parameters: # parameters are shown up in ADO UI in a build queue time
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

- name: publishSymbols
  displayName: 'Publish symbols'
  type: boolean
  default: false

- name: CurrentNetFxVersion
  displayName: 'Lowest supported .NET Framework version (MDS validation)'
  type: string
  default: 'net462'

- name: isPreview
  displayName: 'Is this a preview build?'
  type: boolean
  default: false

# The timeout, in minutes, for each test job.
- name: testJobTimeout
  displayName: 'Test job timeout (in minutes)'
  type: number
  default: 60

# Build parameters — control which packages to build.
# Default to true for CI/scheduled builds; toggle at queue time for selective builds.
- name: buildSqlServerServer
  displayName: 'Build Microsoft.SqlServer.Server'
  type: boolean
  default: true

- name: buildAKVProvider
  displayName: 'Build Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider'
  type: boolean
  default: true

# Release parameters — select which packages to publish to NuGet.
# All default to false; toggle at queue time for on-demand selective release.
- name: releaseSqlServerServer
  displayName: 'Release Microsoft.SqlServer.Server'
  type: boolean
  default: false

- name: releaseLogging
  displayName: 'Release Microsoft.Data.SqlClient.Extensions.Logging'
  type: boolean
  default: false

- name: releaseAbstractions
  displayName: 'Release Microsoft.Data.SqlClient.Extensions.Abstractions'
  type: boolean
  default: false

- name: releaseSqlClient
  displayName: 'Release Microsoft.Data.SqlClient'
  type: boolean
  default: false

- name: releaseExtAzure
  displayName: 'Release Microsoft.Data.SqlClient.Extensions.Azure'
  type: boolean
  default: false

- name: releaseAKVProvider
  displayName: 'Release Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider'
  type: boolean
  default: false

variables:
  - template: /eng/pipelines/libraries/variables.yml@self

  - name: mdsArtifactName
    value: drop_buildMDS_build_signed_package
  - name: PublishSymbols
    value: ${{ parameters['publishSymbols'] }}
  - name: CurrentNetFxVersion
    value: ${{ parameters['CurrentNetFxVersion'] }}

  # AKV job variables
  - name: PACKAGE_NAME
    value: 'Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider'
  - name: apiScanDllPath
    value: '$(Build.SourcesDirectory)/apiScan/dlls'
  - name: apiScanPdbPath
    value: '$(Build.SourcesDirectory)/apiScan/pdbs'

  # Resolved package versions: use preview versions when isPreview is true
  - ${{ if parameters.isPreview }}:
    - name: effectiveLoggingVersion
      value: $(loggingPackagePreviewVersion)
    - name: effectiveAbstractionsVersion
      value: $(abstractionsPackagePreviewVersion)
    - name: effectiveAzureVersion
      value: $(azurePackagePreviewVersion)
    - name: effectiveSqlServerVersion
      value: $(sqlServerPackagePreviewVersion)
    - name: effectiveAkvVersion
      value: $(akvPackagePreviewVersion)
  - ${{ else }}:
    - name: effectiveLoggingVersion
      value: $(loggingPackageVersion)
    - name: effectiveAbstractionsVersion
      value: $(abstractionsPackageVersion)
    - name: effectiveAzureVersion
      value: $(azurePackageVersion)
    - name: effectiveSqlServerVersion
      value: $(sqlServerPackageVersion)
    - name: effectiveAkvVersion
      value: $(akvPackageVersion)

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: /v2/OneBranch.Official.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    featureFlags:
      # Suggested by MerlinBot (https://sqlclientdrivers.visualstudio.com/ADO.Net/_git/dotnet-sqlclient/pullrequest/4882)
      EnableCDPxPAT: false
      WindowsHostVersion: 1ESWindows2022
    globalSdl: # https://aka.ms/obpipelines/sdl
      tsa:
        # The OneBranch template will set 'break' to false for the other SDL
        # tools when TSA is enabled.  This allows TSA to gather the results
        # and publish them for downstream analysis.
        enabled: true
      apiscan:
        enabled: true
        softwareFolder: $(softwareFolder)
        symbolsFolder: $(symbolsFolder)
        softwarename: Microsoft.Data.SqlClient
        versionNumber: $(mdsAssemblyFileVersion)
      codeql:
        compiled:
        enabled: ${{ not(parameters['isPreview']) }}
      sbom:
        enabled: ${{ not(parameters['isPreview']) }}
        packageName: Microsoft.Data.SqlClient
        packageVersion: $(mdsPackageVersion)
      policheck:
        enabled: ${{ not(parameters['isPreview']) }}
        break: true # always break the build on policheck issues. You can disable it by setting to 'false'
        exclusionsFile: $(REPOROOT)\.config\PolicheckExclusions.xml
      asyncSdl:
        enabled: false
        credscan:
          enabled: ${{ not(parameters['isPreview']) }}
          suppressionsFile: $(REPOROOT)/.config/CredScanSuppressions.json
        binskim:
          enabled: ${{ not(parameters['isPreview']) }}
        armory:
          enabled: ${{ not(parameters['isPreview']) }}
          break: true
        eslint: # TypeScript and JavaScript
          enabled: false
        roslyn:
          enabled: ${{ not(parameters['isPreview']) }}
          break: true
        publishLogs:
          enabled: ${{ not(parameters['isPreview']) }}
        tsaOptionsPath: $(REPOROOT)\.config\tsaoptions.json
        disableLegacyManifest: true
    stages:
    # ------------------------------------------------------------------
    # Stage 1: Independent packages (no cross-package dependencies)
    # Logging, Abstractions, and SqlServer.Server build in parallel.
    # ------------------------------------------------------------------
    - stage: build_independent
      displayName: 'Build Independent Packages'
      jobs:
      - template: /eng/pipelines/jobs/build-signed-csproj-package-job.yml@self
        parameters:
          packageDisplayName: Logging
          buildTarget: BuildLogging
          versionProperties: >-
            -p:LoggingPackageVersion=$(effectiveLoggingVersion)
            -p:LoggingAssemblyFileVersion=$(loggingAssemblyFileVersion)
          dllSigningPattern: 'Microsoft.Data.SqlClient.Extensions.Logging.dll'
          softwareName: 'Microsoft.Data.SqlClient.Extensions.Logging'
          assemblyFileVersion: $(loggingAssemblyFileVersion)
          esrpConnectedServiceName: $(ESRPConnectedServiceName)
          esrpClientId: $(ESRPClientId)
          appRegistrationClientId: $(AppRegistrationClientId)
          appRegistrationTenantId: $(AppRegistrationTenantId)
          authAkvName: $(AuthAKVName)
          authSignCertName: $(AuthSignCertName)

      - template: /eng/pipelines/jobs/build-signed-csproj-package-job.yml@self
        parameters:
          packageDisplayName: Abstractions
          buildTarget: BuildAbstractions
          versionProperties: >-
            -p:AbstractionsPackageVersion=$(effectiveAbstractionsVersion)
            -p:AbstractionsAssemblyFileVersion=$(abstractionsAssemblyFileVersion)
          dllSigningPattern: 'Microsoft.Data.SqlClient.Extensions.Abstractions.dll'
          softwareName: 'Microsoft.Data.SqlClient.Extensions.Abstractions'
          assemblyFileVersion: $(abstractionsAssemblyFileVersion)
          esrpConnectedServiceName: $(ESRPConnectedServiceName)
          esrpClientId: $(ESRPClientId)
          appRegistrationClientId: $(AppRegistrationClientId)
          appRegistrationTenantId: $(AppRegistrationTenantId)
          authAkvName: $(AuthAKVName)
          authSignCertName: $(AuthSignCertName)

      - ${{ if eq(parameters.buildSqlServerServer, true) }}:
        - template: /eng/pipelines/jobs/build-signed-sqlserver-package-job.yml@self
          parameters:
            assemblyFileVersion: $(sqlServerAssemblyFileVersion)
            packageVersion: $(effectiveSqlServerVersion)
            nuspecPath: $(sqlServerNuspecPath)
            esrpConnectedServiceName: $(ESRPConnectedServiceName)
            esrpClientId: $(ESRPClientId)
            appRegistrationClientId: $(AppRegistrationClientId)
            appRegistrationTenantId: $(AppRegistrationTenantId)
            authAkvName: $(AuthAKVName)
            authSignCertName: $(AuthSignCertName)

    # ------------------------------------------------------------------
    # Stage 2: Core packages (depend on independent packages)
    # MDS and Extensions.Azure build in parallel after Stage 1 completes.
    # Stage name kept as 'buildMDS' for validate job compatibility.
    # ------------------------------------------------------------------
    - stage: buildMDS
      displayName: 'Build Core Packages'
      dependsOn: build_independent
      jobs:
      - template: /eng/pipelines/common/templates/jobs/build-signed-package-job.yml@self
        parameters:
          symbolsFolder: $(symbolsFolder)
          softwareFolder: $(softwareFolder)
          publishSymbols: ${{ parameters['publishSymbols'] }}
          isPreview: ${{ parameters['isPreview'] }}

      - template: /eng/pipelines/jobs/build-signed-csproj-package-job.yml@self
        parameters:
          packageDisplayName: Azure
          buildTarget: BuildAzure
          versionProperties: >-
            -p:AzurePackageVersion=$(effectiveAzureVersion)
            -p:AzureAssemblyFileVersion=$(azureAssemblyFileVersion)
            -p:AbstractionsPackageVersion=$(effectiveAbstractionsVersion)
          dllSigningPattern: 'Microsoft.Data.SqlClient.Extensions.Azure.dll'
          softwareName: 'Microsoft.Data.SqlClient.Extensions.Azure'
          assemblyFileVersion: $(azureAssemblyFileVersion)
          esrpConnectedServiceName: $(ESRPConnectedServiceName)
          esrpClientId: $(ESRPClientId)
          appRegistrationClientId: $(AppRegistrationClientId)
          appRegistrationTenantId: $(AppRegistrationTenantId)
          authAkvName: $(AuthAKVName)
          authSignCertName: $(AuthSignCertName)

    # ------------------------------------------------------------------
    # Stage 3: Add-on packages (depend on core packages)
    # AKV Provider builds after MDS completes.
    # ------------------------------------------------------------------
    - ${{ if eq(parameters.buildAKVProvider, true) }}:
      - stage: build_addons
        displayName: 'Build Add-on Packages'
        dependsOn: buildMDS
        jobs:
        - template: /eng/pipelines/jobs/build-akv-official-job.yml@self
          parameters:
            akvAssemblyFileVersion: $(akvAssemblyFileVersion)
            akvPackageVersion: $(effectiveAkvVersion)
            apiScanDllPath: $(apiScanDllPath)
            apiScanPdbPath: $(apiScanPdbPath)
            buildConfiguration: Release
            mdsPackageVersion: $(akvMdsPackageVersion)
            publishSymbols: ${{ parameters['publishSymbols'] }}
            appRegistrationClientId: $(appRegistrationClientId)
            appRegistrationTenantId: $(appRegistrationTenantId)
            authAkvName: $(AuthAkvName)
            authSignCertName: $(AuthSignCertName)
            esrpClientId: $(EsrpClientId)
            esrpConnectedServiceName: $(EsrpConnectedServiceName)
            symbolsAzureSubscription: $(SymbolsAzureSubscription)
            symbolsPublishProjectName: $(SymbolsPublishProjectName)
            symbolsPublishServer: $(SymbolsPublishServer)
            symbolsPublishTokenUri: $(SymbolsPublishTokenUri)
            symbolsUploadAccount: $(SymbolsUploadAccount)

    # ------------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------------
    - stage: mds_package_validation
      displayName: 'MDS Package Validation'
      dependsOn: buildMDS
      jobs:
      - template: /eng/pipelines/common/templates/jobs/validate-signed-package-job.yml@self
        parameters:
          artifactName: $(mdsArtifactName)
          isPreview: ${{ parameters['isPreview'] }}

    # ------------------------------------------------------------------
    # Release Stage — on-demand selective publish to NuGet
    # Compile-time conditional: stage is removed entirely when no release
    # parameters are selected, avoiding OneBranch validation errors.
    # When at least one package is selected, a manual approval gate
    # (3-day timeout) lets the team decide whether to release AFTER
    # reviewing the build.  Only designated approvers are notified.
    # ------------------------------------------------------------------
    - ${{ if or(parameters.releaseSqlServerServer, parameters.releaseLogging, parameters.releaseAbstractions, parameters.releaseSqlClient, parameters.releaseExtAzure, parameters.releaseAKVProvider) }}:
      - stage: release
        displayName: 'Release to NuGet'
        dependsOn:
          - ${{ if eq(parameters.buildAKVProvider, true) }}:
            - build_addons
          - buildMDS
          - mds_package_validation
        jobs:
        # Manual approval gate — blocks until a designated approver
        # reviews and approves the release.  The gate stays open for
        # 3 days (4320 min) so you can decide well after the build.
        - job: manual_approval
          displayName: 'Manual Approval'
          dependsOn: []
          pool: server
          steps:
          - task: ManualValidation@0
            displayName: 'Approve NuGet Release'
            timeoutInMinutes: 4320
            inputs:
              notifyUsers: 'cmalhotra;paulmedynski'
              instructions: >-
                Review build $(Build.BuildNumber) and approve to publish
                selected packages to NuGet.
                Selected packages:
                SqlServer.Server=${{ parameters.releaseSqlServerServer }},
                Logging=${{ parameters.releaseLogging }},
                Abstractions=${{ parameters.releaseAbstractions }},
                SqlClient=${{ parameters.releaseSqlClient }},
                Extensions.Azure=${{ parameters.releaseExtAzure }},
                AKV Provider=${{ parameters.releaseAKVProvider }}.

        # Conditional publish jobs — one per package, gated by its release
        # parameter.  Each depends on manual_approval so nothing publishes
        # until an approver explicitly approves.
        - ${{ if eq(parameters.releaseSqlServerServer, true) }}:
          - template: /eng/pipelines/common/templates/jobs/publish-nuget-package-job.yml@self
            parameters:
              packageDisplayName: SqlServer.Server
              artifactName: drop_build_independent_build_signed_sqlserver_package
              nugetServiceConnection: $(NuGetServiceConnection)
              dependsOn: manual_approval
              condition: succeeded('manual_approval')

        - ${{ if eq(parameters.releaseLogging, true) }}:
          - template: /eng/pipelines/common/templates/jobs/publish-nuget-package-job.yml@self
            parameters:
              packageDisplayName: Logging
              artifactName: drop_build_independent_build_signed_Logging_package
              nugetServiceConnection: $(NuGetServiceConnection)
              dependsOn: manual_approval
              condition: succeeded('manual_approval')

        - ${{ if eq(parameters.releaseAbstractions, true) }}:
          - template: /eng/pipelines/common/templates/jobs/publish-nuget-package-job.yml@self
            parameters:
              packageDisplayName: Abstractions
              artifactName: drop_build_independent_build_signed_Abstractions_package
              nugetServiceConnection: $(NuGetServiceConnection)
              dependsOn: manual_approval
              condition: succeeded('manual_approval')

        - ${{ if eq(parameters.releaseSqlClient, true) }}:
          - template: /eng/pipelines/common/templates/jobs/publish-nuget-package-job.yml@self
            parameters:
              packageDisplayName: SqlClient
              artifactName: drop_buildMDS_build_signed_package
              nugetServiceConnection: $(NuGetServiceConnection)
              dependsOn: manual_approval
              condition: succeeded('manual_approval')

        - ${{ if eq(parameters.releaseExtAzure, true) }}:
          - template: /eng/pipelines/common/templates/jobs/publish-nuget-package-job.yml@self
            parameters:
              packageDisplayName: Extensions.Azure
              artifactName: drop_buildMDS_build_signed_Azure_package
              nugetServiceConnection: $(NuGetServiceConnection)
              dependsOn: manual_approval
              condition: succeeded('manual_approval')

        - ${{ if eq(parameters.releaseAKVProvider, true) }}:
          - template: /eng/pipelines/common/templates/jobs/publish-nuget-package-job.yml@self
            parameters:
              packageDisplayName: AKVProvider
              artifactName: drop_build_addons_buildSignedAkvPackage
              nugetServiceConnection: $(NuGetServiceConnection)
              dependsOn: manual_approval
              condition: succeeded('manual_approval')
