#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################
parameters:
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

- name: targetFrameworks
  displayName: 'Target Frameworks on Windows'
  type: object
  default: [net462, net8.0, net9.0]

- name: targetFrameworksLinux
  displayName: 'Target Frameworks on Non-Windows'
  type: object
  default: [net8.0, net9.0]

- name: netcoreVersionTestUtils
  displayName: 'Netcore Version for Test Utilities'
  type: object
  default: net8.0

- name: buildPlatforms
  displayName: 'Build Platforms on Windows'
  type: object
  default: [AnyCPU]

- name: testSets
  displayName: 'Test Sets'
  type: object
  default: [1, 2, 3]

- name: useManagedSNI
  displayName: |
    Use Managed/Native SNI on Windows,
    values [false, true], [false] or [true] are allowed
  type: object
  default: [false, true]

- name: codeCovTargetFrameworks
  displayName: 'Code Coverage Target Frameworks'
  type: object
  default: [net462, net8.0]

- name: buildType
  displayName: 'Build Type'
  default: Project
  values:
    - Project
    - Package

- name: defaultPoolName
  type: string
  default: $(ci_var_defaultPoolName)

variables:
  - template: libraries/ci-build-variables.yml@self

  - name: artifactName
    value: Artifacts

  - name: defaultHostedPoolName
    value: 'Azure Pipelines'

stages:
  - stage: build_nugets
    displayName: 'Build NuGet Packages'
    jobs:
    - template: common/templates/jobs/ci-build-nugets-job.yml@self
      parameters:
        artifactName: $(artifactName)
  - template: common/templates/stages/ci-run-tests-stage.yml@self
    parameters:
      debug: ${{ parameters.debug }}
      buildType: ${{ parameters.buildType }}
      ${{ if eq(parameters.buildType, 'Package') }}:
        dependsOn: build_nugets

      prebuildSteps:
      - template: common/templates/steps/ci-prebuild-step.yml@self
        parameters:
          debug: ${{ parameters.debug }}
          artifactName: $(artifactName)
          buildType: ${{ parameters.buildType }}

      ${{ if eq(parameters.buildType, 'Project') }}:
        postTestJobs:
        - template: common/templates/jobs/ci-code-coverage-job.yml@self
          parameters:
            debug: ${{ parameters.debug }}
            downloadArtifactsSteps:
              - ${{ each targetFramework in parameters.codeCovTargetFrameworks }}:
                - task: DownloadPipelineArtifact@2
                  displayName: 'Download Coverage Reports [${{ targetFramework }}]'
                  inputs:
                    itemPattern: '**\${{ targetFramework }}*'
                    ${{ if contains(targetFramework, 'net4') }}:
                      targetPath: '$(Build.SourcesDirectory)\coverageNetFx'
                    ${{ else }}:
                      targetPath: '$(Build.SourcesDirectory)\coverageNetCore'

      testConfigurations:
        windows_sql_19:
          pool: ${{parameters.defaultPoolName }}
          hostedPool: false
          images:
            Win22_Sql19: ADO-MMS22-SQL19
          TargetFrameworks: ${{parameters.targetFrameworks }}
          netcoreVersionTestUtils: ${{parameters.netcoreVersionTestUtils }}
          buildPlatforms: ${{parameters.buildPlatforms }}
          testSets: ${{parameters.testSets }}
          useManagedSNI: ${{parameters.useManagedSNI }}
          codeCovTargetFrameworks: ${{parameters.codeCovTargetFrameworks }}
          configSqlFor: local
          operatingSystem: Windows
          configProperties:
            TCPConnectionString: $(SQL_TCP_CONN_STRING)
            NPConnectionString: $(SQL_NP_CONN_STRING)
            AADAuthorityURL: $(AADAuthorityURL)
            AADPasswordConnectionString: $(AAD_PASSWORD_CONN_STR)
            AADServicePrincipalId: $(AADServicePrincipalId)
            AADServicePrincipalSecret: $(AADServicePrincipalSecret)
            AzureKeyVaultUrl: $(AzureKeyVaultUrl)
            AzureKeyVaultTenantId: $(AzureKeyVaultTenantId)
            SupportsIntegratedSecurity: $(SupportsIntegratedSecurity)
            UserManagedIdentityClientId: $(UserManagedIdentityClientId)
            FileStreamDirectory: $(FileStreamDirectory)
            LocalDbAppName: $(LocalDbAppName)
            LocalDbSharedInstanceName: $(LocalDbSharedInstanceName)
            AliasName: $(SQLAliasName)
            x86TestTargetFrameworks: [net8.0]
            SQLRootPath: $(SQL19RootPath)
            enableLocalDB: true

        windows_sql_22: 
          pool: ${{parameters.defaultPoolName }}
          images:
            Win22_Sql22: ADO-MMS22-SQL22 
          TargetFrameworks: ${{parameters.targetFrameworks }}
          netcoreVersionTestUtils: ${{parameters.netcoreVersionTestUtils }}
          buildPlatforms: ${{parameters.buildPlatforms }}
          testSets: ${{parameters.testSets }}
          useManagedSNI: ${{parameters.useManagedSNI }}
          codeCovTargetFrameworks: ${{parameters.codeCovTargetFrameworks }}
          configSqlFor: local
          operatingSystem: Windows
          configProperties:
            TCPConnectionString: $(SQL_TCP_CONN_STRING)
            NPConnectionString: $(SQL_NP_CONN_STRING)
            AADAuthorityURL: $(AADAuthorityURL)
            AADPasswordConnectionString: $(AAD_PASSWORD_CONN_STR)
            AADServicePrincipalId: $(AADServicePrincipalId)
            AADServicePrincipalSecret: $(AADServicePrincipalSecret)
            AzureKeyVaultUrl: $(AzureKeyVaultUrl)
            AzureKeyVaultTenantId: $(AzureKeyVaultTenantId)
            SupportsIntegratedSecurity: $(SupportsIntegratedSecurity)
            UserManagedIdentityClientId: $(UserManagedIdentityClientId)
            FileStreamDirectory: $(FileStreamDirectory)
            LocalDbAppName: $(LocalDbAppName)
            LocalDbSharedInstanceName: $(LocalDbSharedInstanceName)
            AliasName: $(SQLAliasName)
            x86TestTargetFrameworks: [net462]
            SQLRootPath: $(SQL22RootPath)
            enableLocalDB: true


        windows_sql_22_named_instance:
          pool: ${{parameters.defaultPoolName }}
          images:
            Win22_Sql22_named_instance: ADO-MMS22-SQL22-WITH-NAMED-INSTANCE
          TargetFrameworks: ${{parameters.targetFrameworks }}
          netcoreVersionTestUtils: ${{parameters.netcoreVersionTestUtils }}
          buildPlatforms: ${{parameters.buildPlatforms }}
          testSets: ${{parameters.testSets }}
          useManagedSNI: ${{parameters.useManagedSNI }}
          codeCovTargetFrameworks: ${{parameters.codeCovTargetFrameworks }}
          configSqlFor: local
          operatingSystem: Windows
          configProperties:
            TCPConnectionString: $(SQL_TCP_INSTANCE_CONN_STRING)
            NPConnectionString: $(SQL_NP_INSTANCE_CONN_STRING)
            SupportsIntegratedSecurity: $(SupportsIntegratedSecurity)
            SQLRootPath: $(SQL22RootPath)
            instanceName: $(NamedInstance)


        windows_azure_sql:
          pool: ${{parameters.defaultPoolName }} 
          images: 
            Win22_Azure_Sql: ADO-MMS22-SQL19
            win11_Azure_Sql: ADO-CI-Win11
          TargetFrameworks: ${{parameters.targetFrameworks }}
          netcoreVersionTestUtils: ${{parameters.netcoreVersionTestUtils }}
          buildPlatforms: ${{parameters.buildPlatforms }}
          testSets: ${{parameters.testSets }}
          useManagedSNI: ${{parameters.useManagedSNI }}
          codeCovTargetFrameworks: ${{parameters.codeCovTargetFrameworks }}
          configSqlFor: azure
          operatingSystem: Windows
          configProperties:
            TCPConnectionString: $(AZURE_DB_TCP_CONN_STRING)
            NPConnectionString: $(AZURE_DB_NP_CONN_STRING)
            AADAuthorityURL: $(AADAuthorityURL)
            AADPasswordConnectionString: $(AAD_PASSWORD_CONN_STR)
            AADServicePrincipalId: $(AADServicePrincipalId)
            AADServicePrincipalSecret: $(AADServicePrincipalSecret)
            AzureKeyVaultUrl: $(AzureKeyVaultUrl)
            AzureKeyVaultTenantId: $(AzureKeyVaultTenantId)
            SupportsIntegratedSecurity: false
            UserManagedIdentityClientId: $(UserManagedIdentityClientId)
            LocalDbAppName: $(LocalDbAppName)
            LocalDbSharedInstanceName: $(LocalDbSharedInstanceName)

        windows_azure_arm64_sql:
          pool: ADO-CI-PUBLIC-ARM64-1ES-EUS-POOL
          images: 
            Win22_Azure_ARM64_Sql: ADO-WIN11-ARM64
          TargetFrameworks: ${{parameters.targetFrameworks }}
          netcoreVersionTestUtils: ${{parameters.netcoreVersionTestUtils }}
          buildPlatforms: ${{parameters.buildPlatforms }}
          testSets: ${{parameters.testSets }}
          useManagedSNI: ${{parameters.useManagedSNI }}
          codeCovTargetFrameworks: ${{parameters.codeCovTargetFrameworks }}
          configSqlFor: azure
          operatingSystem: Windows
          configProperties:
            TCPConnectionString: $(AZURE_DB_TCP_CONN_STRING_eastus)
            NPConnectionString: $(AZURE_DB_NP_CONN_STRING_eastus)
            AADAuthorityURL: $(AADAuthorityURL)
            AADPasswordConnectionString: $(AAD_PASSWORD_CONN_STR_eastus)
            AADServicePrincipalId: $(AADServicePrincipalId)
            AADServicePrincipalSecret: $(AADServicePrincipalSecret)
            AzureKeyVaultUrl: $(AzureKeyVaultUrl)
            AzureKeyVaultTenantId: $(AzureKeyVaultTenantId)
            SupportsIntegratedSecurity: false
            UserManagedIdentityClientId: $(UserManagedIdentityClientId_eastus)
            LocalDbAppName: $(LocalDbAppName)
            LocalDbSharedInstanceName: $(LocalDbSharedInstanceName)

        windows_enclave_sql:
          pool: ADO-CI-AE-1ES-Pool
          images: 
            Win22_Enclave_Sql19: ADO-MMS22-SQL19
          TargetFrameworks: ${{parameters.targetFrameworks }}
          netcoreVersionTestUtils: ${{parameters.netcoreVersionTestUtils }}
          buildPlatforms: ${{parameters.buildPlatforms }}
          testSets: [AE]
          useManagedSNI: ${{parameters.useManagedSNI }}
          codeCovTargetFrameworks: ${{parameters.codeCovTargetFrameworks }}
          configSqlFor: enclave
          operatingSystem: Windows
          configProperties:
            TCPConnectionStringHGSVBS: $(SQL_TCP_CONN_STRING_HGSVBS)
            TCPConnectionStringNoneVBS: $(SQL_TCP_CONN_STRING_NoneVBS)
            TCPConnectionStringAASSGX: $(SQL_TCP_CONN_STRING_AASSGX)
            EnclaveEnabled: true
            AADAuthorityURL: $(AADAuthorityURL)
            AADPasswordConnectionString: $(AAD_PASSWORD_CONN_STR)
            AADServicePrincipalId: $(AADServicePrincipalId)
            AADServicePrincipalSecret: $(AADServicePrincipalSecret)
            AzureKeyVaultUrl: $(AzureKeyVaultUrl)
            AzureKeyVaultTenantId: $(AzureKeyVaultTenantId)
            SupportsIntegratedSecurity: $(SupportsIntegratedSecurity)
            UserManagedIdentityClientId: $(UserManagedIdentityClientId)
            AliasName: $(SQLAliasName)            
            LocalDbAppName: $(LocalDbAppName)
            LocalDbSharedInstanceName: $(LocalDbSharedInstanceName)

        linux_sql_19_22:
          pool: ${{parameters.defaultPoolName }}
          images:
            Ubuntu20_Sql22: ADO-UB20-SQL22
          TargetFrameworks: ${{parameters.targetFrameworksLinux }}
          netcoreVersionTestUtils: ${{parameters.netcoreVersionTestUtils }}
          buildPlatforms: [AnyCPU]
          testSets: ${{parameters.testSets }}
          useManagedSNI: [true]
          codeCovTargetFrameworks: ${{parameters.codeCovTargetFrameworks }}
          configSqlFor: local
          operatingSystem: Linux
          configProperties:
            TCPConnectionString: $(SQL_TCP_CONN_STRING)
            NPConnectionString: $(SQL_NP_CONN_STRING)
            AADServicePrincipalSecret: $(AADServicePrincipalSecret)
            AzureKeyVaultUrl: $(AzureKeyVaultUrl)
            AzureKeyVaultTenantId: $(AzureKeyVaultTenantId)
            SupportsIntegratedSecurity: false
            UserManagedIdentityClientId: $(UserManagedIdentityClientId)
            LocalDbAppName: $(LocalDbAppName)
            LocalDbSharedInstanceName: $(LocalDbSharedInstanceName)
            AliasName: $(SQLAliasName)

        linux_azure_sql:
          pool: ${{parameters.defaultPoolName }}
          images:
            Ubuntu20_Azure_Sql: ADO-UB20-Sql22
          TargetFrameworks: ${{parameters.targetFrameworksLinux }}
          netcoreVersionTestUtils: ${{parameters.netcoreVersionTestUtils }}
          buildPlatforms: [AnyCPU]
          testSets: ${{parameters.testSets }}
          useManagedSNI: [true]
          codeCovTargetFrameworks: ${{parameters.codeCovTargetFrameworks }}
          configSqlFor: azure
          operatingSystem: Linux
          configProperties:
            TCPConnectionString: $(AZURE_DB_TCP_CONN_STRING)
            NPConnectionString: $(AZURE_DB_NP_CONN_STRING)
            AADAuthorityURL: $(AADAuthorityURL)
            AADPasswordConnectionString: $(AAD_PASSWORD_CONN_STR)
            AADServicePrincipalId: $(AADServicePrincipalId)
            AADServicePrincipalSecret: $(AADServicePrincipalSecret)
            AzureKeyVaultUrl: $(AzureKeyVaultUrl)
            AzureKeyVaultTenantId: $(AzureKeyVaultTenantId)
            SupportsIntegratedSecurity: false
            UserManagedIdentityClientId: $(UserManagedIdentityClientId)
            LocalDbAppName: $(LocalDbAppName)
            LocalDbSharedInstanceName: $(LocalDbSharedInstanceName)

        linux_enclave_sql:
          pool: ADO-CI-AE-1ES-Pool
          images:
            Ubuntu20_Enclave_Sql19: ADO-UB20-Sql22
          TargetFrameworks: ${{parameters.targetFrameworksLinux }}
          netcoreVersionTestUtils: ${{parameters.netcoreVersionTestUtils }}
          buildPlatforms: [AnyCPU]
          testSets: [AE]
          useManagedSNI: [true]
          codeCovTargetFrameworks: ${{parameters.codeCovTargetFrameworks }}
          configSqlFor: enclave
          operatingSystem: Linux
          configProperties:
            TCPConnectionStringHGSVBS: $(SQL_TCP_CONN_STRING_HGSVBS)
            TCPConnectionStringNoneVBS: $(SQL_TCP_CONN_STRING_NoneVBS)
            TCPConnectionStringAASSGX: $(SQL_TCP_CONN_STRING_AASSGX)
            EnclaveEnabled: true
            AADAuthorityURL: $(AADAuthorityURL)
            AADPasswordConnectionString: $(AAD_PASSWORD_CONN_STR)
            AADServicePrincipalId: $(AADServicePrincipalId)
            AADServicePrincipalSecret: $(AADServicePrincipalSecret)
            AzureKeyVaultUrl: $(AzureKeyVaultUrl)
            AzureKeyVaultTenantId: $(AzureKeyVaultTenantId)
            SupportsIntegratedSecurity: false
            UserManagedIdentityClientId: $(UserManagedIdentityClientId)
            LocalDbAppName: $(LocalDbAppName)
            LocalDbSharedInstanceName: $(LocalDbSharedInstanceName)

        mac_azure_sql:
          pool: $(defaultHostedPoolName)
          hostedPool: true
          images:
            MacOSLatest_Azure_Sql: macos-latest
          TargetFrameworks: ${{parameters.targetFrameworksLinux }}
          netcoreVersionTestUtils: ${{parameters.netcoreVersionTestUtils }}
          buildPlatforms: [AnyCPU]
          testSets: ${{parameters.testSets }}
          useManagedSNI: [true]
          codeCovTargetFrameworks: ${{parameters.codeCovTargetFrameworks }}
          configSqlFor: azure
          operatingSystem: Mac
          configProperties:
            TCPConnectionString: $(AZURE_DB_SP_TCP_CONN_STRING)
            NPConnectionString: $(AZURE_DB_SP_NP_CONN_STRING)
            SupportsIntegratedSecurity: false
            ManagedIdentitySupported: false
            LocalDbAppName: $(LocalDbAppName)
            LocalDbSharedInstanceName: $(LocalDbSharedInstanceName)
