#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################

# This pipeline builds and tests the following packages using project
# references:
#
#   - Microsoft.SqlServer.Server
#   - Microsoft.Data.SqlClient
#   - Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider
#
# It runs via CI push triggers and schedules and uses the Release build
# configuration:
#
#   - Commits to GitHub main
#   - Commits to ADO internal/main
#   - Weekdays at 01:00 UTC on GitHub main
#   - Thursdays at 05:00 UTC on ADO internal/main
#
# GOTCHA: This pipeline definition is triggered by GitHub _and_ ADO CI.  We are
# able to define different triggers and schedules using branch filters:
#
#   - Only the GitHub repo has a 'main' branch, so its presence indicates that
#     the pipeline run was triggered via GitHub.
#
#   - Only the ADO repo has an 'internal/main' branch.
#
# Changes are batched together to ensure that the pipline never runs
# concurrently.
#
# This pipeline definition is mapped to the following Azure DevOps pipelines:
#
# - CI-SqlClient in the Public project:
#
#   https://sqlclientdrivers.visualstudio.com/public/_build?definitionId=1879
#
# - MDS Main CI in the ADO.net project:
#
#   https://sqlclientdrivers.visualstudio.com/ADO.Net/_build?definitionId=1825

# Set the pipeline run name to the day-of-year and the daily run counter.
name: $(DayOfYear)$(Rev:rr)

# Do not trigger this pipeline for PRs.
pr: none

# Trigger this pipeline on commits to certain branches.
trigger:
  
  # Don't trigger a new run until the previous one completes.  This may cause
  # multiple commits to be batched into a single run.
  batch: true
  
  branches:
    include:
    # GitHub main branch.
    - main

    # ADO internal/main branch.
    - internal/main
  
  paths:
    include:
    - .azuredevops
    - .config
    - doc
    - eng/pipelines
    - src
    - tools
    - azurepipelines-coverage.yml
    - build.proj
    - NuGet.config

# Trigger this pipline on a schedule.
schedules:

  # GitHub main on weekdays
  - cron: '0 1 * * Mon-Fri'
    displayName: Weekday Run (Release Config)
    branches:
      include:
      - main
    always: true

  # ADO internal/main on Thursdays.
  - cron: '0 5 * * Thu'
    displayName: Thursday Run (Release Config)
    branches:
      include:
      - internal/main
    always: true

# Pipeline parameters, visible in the Azure DevOps UI.
parameters:

  # The build configuration to use; defaults to Release.
  - name: buildConfiguration
    displayName: Build Configuration
    type: string
    default: Release
    values:
      - Debug
      - Release

  - name: buildPlatforms
    displayName: Build Platforms on Windows
    type: object
    default: [AnyCPU]

  - name: codeCovTargetFrameworks
    displayName: Code Coverage Target Frameworks
    type: object
    default: [net462, net8.0, net9.0]

  - name: uploadCodeCov
    displayName: 'Upload Code Coverage to CodeCov'
    type: boolean
    default: true

  - name: debug
    displayName: Enable debug output
    type: boolean
    default: false

  # The target frameworks to build and run tests for on Windows.
  #
  # These are _not_ the target frameworks to build the driver packages for.
  #
  # Note: We are excluding .NET 10.0 here to avoid consuming too many resources
  # during PR pipeline runs, and until we update our 1ES images to include
  # Visual Studio 2026 (18.0) whose MSBuild SDK supports .NET 10.
  #
  - name: targetFrameworks
    displayName: Target Frameworks on Windows
    type: object
    default: [net462, net8.0, net9.0]

  # The target frameworks to build and run tests for on Unix.
  #
  # These are _not_ the target frameworks to build the driver packages for.
  #
  # Note: We are excluding .NET 10.0 here to avoid consuming too many resources
  # during PR pipeline runs, and until we update our 1ES images to include
  # Visual Studio 2026 (18.0) whose MSBuild SDK supports .NET 10.
  #
  - name: targetFrameworksUnix
    displayName: Target Frameworks on Unix
    type: object
    default: [net8.0, net9.0]

  - name: testSets
    displayName: Test Sets
    type: object
    default: [1, 2, 3]

  # The timeout, in minutes, for each test job.
  - name: testJobTimeout
    displayName: Test job timeout (in minutes)
    type: string
    default: Default

  - name: useManagedSNI
    displayName: |
      Use Managed/Native SNI on Windows,
      values [false, true], [false] or [true] are allowed
    type: object
    default: [false, true]

extends:
  template: dotnet-sqlclient-ci-core.yml@self
  parameters:
    buildConfiguration: ${{ parameters.buildConfiguration }}
    buildPlatforms: ${{ parameters.buildPlatforms }}
    buildType: Project
    codeCovTargetFrameworks: ${{ parameters.codeCovTargetFrameworks }}
    uploadCodeCov: ${{ parameters.uploadCodeCov }}
    debug: ${{ parameters.debug }}
    targetFrameworks: ${{ parameters.targetFrameworks }}
    targetFrameworksUnix: ${{ parameters.targetFrameworksUnix }}
    testSets: ${{ parameters.testSets }}
    # Populate the actual test job timeout numeric values if Default was
    # specified.  We choose different values depending on the build
    # configuration.
    ${{ if eq(parameters.testJobTimeout, 'Default') }}:
      # If the build configuration is Debug, we allow a bit of extra time since
      # some tests run more slowly, and some tests are Debug only.
      ${{ if eq(parameters.buildConfiguration, 'Debug') }}:
        testJobTimeout: 110
      ${{ else }}:
        testJobTimeout: 90
    ${{ else }}:
      testJobTimeout: ${{ parameters.testJobTimeout }}
    useManagedSNI: ${{ parameters.useManagedSNI }}
