#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################

name: $(Year:YY)$(DayOfYear)$(Rev:.r)

# No automated triggers; this pipeline must be run manually.
pr: none
trigger: none

# These parameters are visible in the Azure DevOps pipeline UI when a new run is queued.
parameters:
  # True to enable debug information and steps.
  - name: debug
    displayName: Enable debug output
    type: boolean
    default: false

  # True if this is a preview build.
  - name: isPreview
    displayName: Is this a preview build?
    type: boolean
    default: false

  # True to publish symbols to private and public servers.
  - name: publishSymbols
    displayName: Publish symbols
    type: boolean
    default: false

  # The timeout, in minutes, for each test job.
  - name: testJobTimeout
    displayName: Test job timeout (in minutes)
    type: number
    default: 60

  # Build parameters — select which packages to build.

  # Build the Microsoft.SqlServer.Server package.
  - name: buildSqlServerServer
    displayName: Build Microsoft.SqlServer.Server
    type: boolean
    default: true

  # Build Microsoft.Data.SqlClient and Extensions packages.
  - name: buildSqlClient
    displayName: Build Microsoft.Data.SqlClient and Extensions
    type: boolean
    default: true

  # Build the Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider package.
  - name: buildAKVProvider
    displayName: Build Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider
    type: boolean
    default: true

  # Release parameters — select which packages to publish to NuGet.
  # All default to false; toggle at queue time for on-demand selective release.

  # Release the Microsoft.SqlServer.Server package.
  - name: releaseSqlServerServer
    displayName: Release Microsoft.SqlServer.Server
    type: boolean
    default: false

  # Release the Microsoft.Data.SqlClient.Extensions.Logging package.
  - name: releaseLogging
    displayName: Release Microsoft.Data.SqlClient.Extensions.Logging
    type: boolean
    default: false

  # Release the Microsoft.Data.SqlClient.Extensions.Abstractions package.
  - name: releaseAbstractions
    displayName: Release Microsoft.Data.SqlClient.Extensions.Abstractions
    type: boolean
    default: false

  # Release the Microsoft.Data.SqlClient package.
  - name: releaseSqlClient
    displayName: Release Microsoft.Data.SqlClient
    type: boolean
    default: false

  # Release the Microsoft.Data.SqlClient.Extensions.Azure package.
  - name: releaseExtAzure
    displayName: Release Microsoft.Data.SqlClient.Extensions.Azure
    type: boolean
    default: false

  # Release the Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider package.
  - name: releaseAKVProvider
    displayName: Release Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider
    type: boolean
    default: false

variables:
  - template: /eng/pipelines/libraries/onebranch-variables.yml@self

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  # See: https://aka.ms/obpipelines/templates
  template: /v2/OneBranch.NonOfficial.CrossPlat.yml@templates
  parameters:
    release:
       # This indicates the pipeline category to deploy Box products.  See:
       # https://eng.ms/docs/products/onebranch/release/yamlreleasepipelines/deployboxproducts
      category: NonAzure
    featureFlags:
      EnableCDPxPAT: false
      WindowsHostVersion: 1ESWindows2022
    # See: https://aka.ms/obpipelines/sdl
    globalSdl:
      tsa:
        # We disable TSA for non-official pipelines.  This inhibits spurious TSA alerts and ADO
        # task creation, since non-official builds are often done against development branches.
        enabled: false
      apiscan:
        enabled: true
        break: false
        # Other ApiScan options are set by the jobs via ob_sdl_apiscan_* variables.
      codeql:
        compiled:
        enabled: true
      sbom:
        enabled: true
        packageName: Microsoft.Data.SqlClient
        packageVersion: $(mdsPackageVersion)
      policheck:
        enabled: true
        break: true
        exclusionsFile: $(REPO_ROOT)\.config\PolicheckExclusions.xml
      asyncSdl:
        enabled: false
        credscan:
          enabled: true
          suppressionsFile: $(REPO_ROOT)/.config/CredScanSuppressions.json
        binskim:
          enabled: true
        armory:
          enabled: true
          break: true
        eslint:
          enabled: false
        roslyn:
          enabled: true
          break: true
        publishLogs:
          enabled: true
        tsaOptionsPath: $(REPO_ROOT)\.config\tsaoptions.json
        disableLegacyManifest: true
    stages:
      - template: /eng/pipelines/stages/sqlclient-onebranch-stages.yml@self
        parameters:
          debug: ${{ parameters.debug }}
          # This is not an official pipeline.
          isOfficial: false
          isPreview: ${{ parameters.isPreview }}
          publishSymbols: ${{ parameters.publishSymbols }}
          # Non-Official pipelines must always be a dry-run.
          releaseDryRun: true
          testJobTimeout: ${{ parameters.testJobTimeout }}
          buildSqlServerServer: ${{ parameters.buildSqlServerServer }}
          buildSqlClient: ${{ parameters.buildSqlClient }}
          buildAKVProvider: ${{ parameters.buildAKVProvider }}
          releaseSqlServerServer: ${{ parameters.releaseSqlServerServer }}
          releaseLogging: ${{ parameters.releaseLogging }}
          releaseAbstractions: ${{ parameters.releaseAbstractions }}
          releaseSqlClient: ${{ parameters.releaseSqlClient }}
          releaseExtAzure: ${{ parameters.releaseExtAzure }}
          releaseAKVProvider: ${{ parameters.releaseAKVProvider }}
