################################################################################
# Licensed to the .NET Foundation under one or more agreements.
# The .NET Foundation licenses this file to you under the MIT license.
# See the LICENSE file in the project root for more information.
################################################################################

# This pipeline runs the stress test suite using the artifacts from the
# triggering pipeline.
#
# It runs after every successful run of the following pipelines:
#
# Public project:
#   - CI-SqlClient-Package (branch main only)
#
# ADO.Net project:
#   - MDS Main CI-Package (branch internal/main only)
#
# This pipeline definition is mapped to the Stress-SqlClient pipelines:
#
# Public project:
#
#   https://dev.azure.com/SqlClientDrivers/public/_build?definitionId=2212
#
# ADO.net project:
#
#   TODO

# Set the pipeline run name to the day-of-year and the daily run counter.
name: $(DayOfYear)$(Rev:rr)

# Do not trigger this pipeline for PRs, commits, or schedules.
pr: none
trigger: none

# Trigger this pipeline after successful runs of each of the following
# pipelines.
#
# The pipeline identifiers are displayed in the Azure DevOps UI, so it is
# helpful if they indicate the project, folder, and pipeline name, hence the
# verbose values below.
#
resources:
  pipelines:

    # TODO: Remove this pipeline; it exists for testing via PR runs.
    - pipeline: Public-ADO-PR-SqlClient-Package
      project: Public
      source: /ADO/PR-SqlClient-Package

    # The CI-SqlClient-Package pipeline in the Public project.
    - pipeline: Public-ADO-CI-SqlClient-Package
      project: Public
      source: /ADO/CI-SqlClient-Package
      trigger:
        branches:
          include:
            - main

    # The MDS Main CI-Package pipeline in the ADO.Net project.
    - pipeline: ADO-Net-Internal-CI-MDS-Main-CI-Package
      project: ADO.Net
      source: /Internal CI/MDS Main CI-Package
      trigger:
        branches:
          include:
            - internal/main

# Pipeline parameters, visible in the Azure DevOps UI.
parameters:

  # The build configuration to use; defaults to Release.
  - name: buildConfiguration
    displayName: Build Configuration
    type: string
    default: Release
    values:
      - Debug
      - Release

  - name: debug
    displayName: Enable debug output
    type: boolean
    default: false

stages:
  - template: /eng/pipelines/stages/stress-tests-ci-stage.yml@self
    parameters:
      buildConfiguration: ${{ parameters.buildConfiguration }}
      # If we were triggered by an upstream pipeline, use the alias of that
      # pipeline resource.  Otherwise, assume we were triggered manually via the
      # Azure DevOps UI and arbitrarily choose use the Public
      # CI-SqlClient-Package pipeline.
      #
      # TODO: Use CI-SqlClient-Package instead of PR-SqlClient-Package.
      pipelineAlias: $[coalesce(variables['Resources.TriggeringAlias'], 'Public-ADO-PR-SqlClient-Package')]
      # All of the pipelines that trigger us produce the same artifact name.
      # (See dotnet-sqlclient-ci-core.yml.)
      pipelineArtifactName: Artifacts
      ${{ if eq(parameters.debug, 'true') }}:
        verbosity: 'detailed'
