// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System;

namespace Microsoft.Data.SqlClient.Reliability
{
    /// <summary>
    /// It retrieves next time interval with respect to the number of retries if transient condition happens.
    /// </summary>
    public interface ISqlRetryLogic
    {
        /// <summary>
        /// Number of retries.
        /// </summary>
        int NumberOfTries { get; }

        /// <summary>
        /// Current retry number.
        /// </summary>
        int Current { get; }

        /// <summary>
        /// The timer interval enumerator.
        /// </summary>
        ISqlRetryIntervalEnumerator RetryIntervalEnumerator { get; }

        /// <summary>
        /// Delegate to a transient condition predicator.
        /// The function that this delegate points to it must return a true value when an expected transient exception happens.
        /// </summary>
        Predicate<Exception> TransientPredicate { get; }

        /// <summary>
        /// Try to get the next interval time by the enumerator if the counter does not exceed from the number of retries.
        /// </summary>
        /// <param name="intervalTime">The interval time that is generated by the enumerator</param>
        /// <returns>True if the number of retries does not exceed unless False</returns>
        bool TryNextInterval(out TimeSpan intervalTime);

        /// <summary>
        /// Set the counters and enumerator to default values for next use.
        /// </summary>
        void Reset();
    }
}
