#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################

parameters:
    - name: akvAssemblyFileVersion
      type: string

    - name: akvPackageVersion
      type: string

    - name: apiScanDllPath
      type: string

    - name: apiScanPdbPath
      type: string

    - name: buildConfiguration
      type: string
      values:
        - Debug
        - Release

    - name: mdsPackageVersion
      type: string

    - name: publishSymbols
      type: boolean

    - name: appRegistrationClientId
      type: string

    - name: appRegistrationTenantId
      type: string

    - name: authAkvName
      type: string

    - name: authSignCertName
      type: string

    - name: esrpClientId
      type: string

    - name: esrpConnectedServiceName
      type: string

    - name: symbolsAzureSubscription
      type: string

    - name: symbolsPublishProjectName
      type: string

    - name: symbolsPublishServer
      type: string

    - name: symbolsPublishTokenUri
      type: string

    - name: symbolsUploadAccount
      type: string

    # @TODO: This should be determined from build output, or at a higher level
    - # Note: not intended to be passed in, is only used for copying files for ApiScan.
      # This is only defined as a parameter since ADO pipelines do not support array variables.
      name: targetFrameworks
      type: object
      default:
          - net462
          - net8.0
          - net9.0

jobs:
    - job: buildSignedAkvPackage
      displayName: 'Build Signed AKV Package'
      pool:
          type: windows

      variables:
          ob_outputDirectory: '$(ARTIFACT_PATH)'
          # APIScan configuration for AKV Provider
          ob_sdl_apiscan_enabled: true
          ob_sdl_apiscan_softwareFolder: '${{ parameters.apiScanDllPath }}'
          ob_sdl_apiscan_symbolsFolder: '${{ parameters.apiScanPdbPath }}'
          ob_sdl_apiscan_softwarename: 'Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider'
          ob_sdl_apiscan_versionNumber: '${{ parameters.akvAssemblyFileVersion }}'

      steps:
          - template: /eng/pipelines/steps/script-output-environment-variables-step.yml@self

          - powershell: |
                $jsonParams = '${{ convertToJson(parameters) }}' -replace '\\', '\\'
                $jsonParams | ConvertFrom-Json | Format-List
            displayName: 'Output Job Parameters'

          # Install the .NET SDK.
          - template: /eng/pipelines/steps/install-dotnet.yml@self

          # Perform analysis before building, since this step will clobber build
          # output.
          - template: /eng/pipelines/steps/roslyn-analyzers-akv-step.yml@self
            parameters:
                akvPackageVersion: '${{ parameters.akvPackageVersion }}'
                buildConfiguration: '${{ parameters.buildConfiguration }}'
                mdsPackageVersion: '${{ parameters.mdsPackageVersion }}'

          - template: /eng/pipelines/steps/compound-build-akv-step.yml@self
            parameters:
                akvAssemblyFileVersion: '${{ parameters.akvAssemblyFileVersion }}'
                akvPackageVersion: '${{ parameters.akvPackageVersion }}'
                buildConfiguration: '${{ parameters.buildConfiguration }}'
                mdsPackageVersion: '${{ parameters.mdsPackageVersion }}'

          - ${{ each targetFramework in parameters.targetFrameworks }}:
              - template: /eng/pipelines/steps/compound-extract-akv-apiscan-files-step.yml@self
                parameters:
                    buildConfiguration: '${{ parameters.buildConfiguration }}'
                    dllPath: '${{ parameters.apiScanDllPath }}'
                    pdbPath: '${{ parameters.apiScanPdbPath }}'
                    referenceType: Package
                    targetFramework: '${{ targetFramework }}'

          - template: /eng/pipelines/steps/compound-esrp-dll-signing-step.yml@self
            parameters:
                appRegistrationClientId: '${{ parameters.AppRegistrationClientId }}'
                appRegistrationTenantId: '${{ parameters.AppRegistrationTenantId }}'
                authAkvName: '${{ parameters.AuthAkvName }}'
                authSignCertName: '${{ parameters.AuthSignCertName }}'
                esrpClientId: '${{ parameters.EsrpClientId }}'
                esrpConnectedServiceName: '${{ parameters.EsrpConnectedServiceName }}'
                pattern: 'Microsoft.Data.SqlClient.AlwaysEncrypted.*.dll'

          - template: /eng/pipelines/steps/compound-nuget-pack-step.yml@self
            parameters:
                buildConfiguration: '${{ parameters.buildConfiguration }}'
                generateSymbolsPackage: true    # Always generate symbols, even if they are not published
                packageVersion: '${{ parameters.akvPackageVersion }}'
                nuspecPath: '$(REPO_ROOT)/tools/specs/add-ons/$(PACKAGE_NAME).nuspec'
                outputDirectory: '$(ARTIFACT_PATH)'
                referenceType: Package
                properties: MdsPackageVersion=${{ parameters.mdsPackageVersion }}

          - template: /eng/pipelines/steps/compound-esrp-nuget-signing-step.yml@self
            parameters:
                appRegistrationClientId: '${{ parameters.AppRegistrationClientId }}'
                appRegistrationTenantId: '${{ parameters.AppRegistrationTenantId }}'
                authAkvName: '${{ parameters.AuthAkvName }}'
                authSignCertName: '${{ parameters.AuthSignCertName }}'
                esrpClientId: '${{ parameters.EsrpClientId }}'
                esrpConnectedServiceName: '${{ parameters.EsrpConnectedServiceName }}'

          - ${{ if parameters.publishSymbols }}:
            - template: /eng/pipelines/steps/compound-publish-symbols-step.yml@self
              parameters:
                  artifactName: 'akv_symbols_$(System.TeamProject)_$(Build.Repository.Name)_$(Build.SourceBranchName)_${{ parameters.akvPackageVersion }}_$(System.TimelineId)'
                  azureSubscription: '${{ parameters.symbolsAzureSubscription }}'
                  publishProjectName: '${{ parameters.symbolsPublishProjectName }}'
                  packageName: '$(PACKAGE_NAME)'
                  publishServer: '${{ parameters.symbolsPublishServer }}'
                  publishToInternal: true
                  publishToPublic: true
                  publishTokenUri: '${{ parameters.symbolsPublishTokenUri }}'
                  referenceType: Package
                  searchPattern: |
                      Windows_NT/${{ parameters.buildConfiguration }}.AnyCPU/AzureKeyVaultProvider/**/$(PACKAGE_NAME).pdb
                      AnyOS/${{ parameters.buildConfiguration }}.AnyCPU/AzureKeyVaultProvider/**/$(PACKAGE_NAME).pdb
                  uploadAccount: '${{ parameters.symbolsUploadAccount }}'
                  version: '${{ parameters.akvPackageVersion }}'
