################################################################################
# Licensed to the .NET Foundation under one or more agreements.  The .NET
# Foundation licenses this file to you under the MIT license.  See the LICENSE
# file in the project root for more information.
################################################################################

# This job packs the Logging package into NuGet and symbols packages and
# publishes them as a named pipeline artifact.
#
# This template defines a job named 'pack_logging_package_job' that can be
# depended on by downstream jobs.

parameters:

  # The name to apply to the published pipeline artifacts.
  - name: loggingArtifactsName
    type: string
    default: Logging.Artifacts

  # The assembly file version to stamp into the Logging DLLs.
  - name: loggingAssemblyFileVersion
    type: string

  # The version to apply to the Logging NuGet package and its assemblies.
  - name: loggingPackageVersion
    type: string

  # The type of build to test (Release or Debug)
  - name: buildConfiguration
    type: string
    values:
    - Release
    - Debug

  # True to enable extra debug steps and logging.
  - name: debug
    type: boolean
    default: false

  # The list of upstream jobs to depend on.
  - name: dependsOn
    type: object
    default: []

  # The verbosity level for the dotnet CLI commands.
  - name: dotnetVerbosity
    type: string
    default: normal
    values:
    - quiet
    - minimal
    - normal
    - detailed
    - diagnostic

jobs:

  - job: pack_logging_package_job
    displayName: Pack Logging Package

    dependsOn: ${{ parameters.dependsOn }}

    pool:
      name: Azure Pipelines
      vmImage: ubuntu-latest

    variables:

      # The Logging project file to use for all dotnet CLI commands.
      - name: project
        value: src/Microsoft.Data.SqlClient.Extensions/Logging/src/Logging.csproj

      # The directory where the NuGet packages will be staged before being
      # published as pipeline artifacts.
      - name: dotnetPackagesDir
        value: $(Build.StagingDirectory)/dotnetPackages

      # Explicitly unset the $PLATFORM environment variable that is set by the
      # 'ADO Build properties' Library in the ADO SqlClientDrivers public project.
      - name: Platform
        value: ''

      # Do the same for $CONFIGURATION since we explicitly set it using our
      # 'buildConfiguration' parameter, and we don't want the environment to
      # override us.
      - name: Configuration
        value: ''

    steps:

      # Emit environment variables if debug is enabled.
      - ${{ if eq(parameters.debug, true) }}:
        - pwsh: 'Get-ChildItem Env: | Sort-Object Name'
          displayName: '[Debug] Print Environment Variables'

      # Install the .NET SDK.
      - template: /eng/pipelines/steps/install-dotnet.yml@self
        parameters:
          debug: ${{ parameters.debug }}

      # Create the NuGet packages.
      - task: DotNetCoreCLI@2
        displayName: Create NuGet Package
        inputs:
          command: pack
          packagesToPack: $(project)
          configurationToPack: ${{ parameters.buildConfiguration }}
          packDirectory: $(dotnetPackagesDir)
          verbosityToPack: ${{ parameters.dotnetVerbosity }}
          buildProperties: >-
            -p:LoggingPackageVersion=${{ parameters.loggingPackageVersion }}
            -p:LoggingAssemblyFileVersion=${{ parameters.loggingAssemblyFileVersion }}

      # Publish the NuGet packages as a named pipeline artifact.
      - task: PublishPipelineArtifact@1
        displayName: Publish Pipeline Artifact
        inputs:
          targetPath: $(dotnetPackagesDir)
          artifactName: ${{ parameters.loggingArtifactsName }}
          publishLocation: pipeline
