//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Data.SqlClient.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Data.SqlClient.UnitTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AlwaysEncrypted_NativeColumnEncryptionKeyBaseline_Certificate {
            get {
                object obj = ResourceManager.GetObject("AlwaysEncrypted_NativeColumnEncryptionKeyBaseline_Certificate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentUser/My/b3c66ffbe1db57419792e24aa970455bfac30757.
        /// </summary>
        internal static string AlwaysEncrypted_NativeColumnEncryptionKeyBaseline_CertificatePath1 {
            get {
                return ResourceManager.GetString("AlwaysEncrypted_NativeColumnEncryptionKeyBaseline_CertificatePath1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentUser/My/b3c66ffbe1db57419792e24aa970455bfac30757.
        /// </summary>
        internal static string AlwaysEncrypted_NativeColumnEncryptionKeyBaseline_CertificatePath2 {
            get {
                return ResourceManager.GetString("AlwaysEncrypted_NativeColumnEncryptionKeyBaseline_CertificatePath2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentUser/My/b3c66ffbe1db57419792e24aa970455bfac30757.
        /// </summary>
        internal static string AlwaysEncrypted_NativeColumnEncryptionKeyBaseline_CertificatePath3 {
            get {
                return ResourceManager.GetString("AlwaysEncrypted_NativeColumnEncryptionKeyBaseline_CertificatePath3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AlwaysEncrypted_NativeColumnEncryptionKeyBaseline_FinalCell1 {
            get {
                object obj = ResourceManager.GetObject("AlwaysEncrypted_NativeColumnEncryptionKeyBaseline_FinalCell1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AlwaysEncrypted_NativeColumnEncryptionKeyBaseline_FinalCell2 {
            get {
                object obj = ResourceManager.GetObject("AlwaysEncrypted_NativeColumnEncryptionKeyBaseline_FinalCell2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AlwaysEncrypted_NativeColumnEncryptionKeyBaseline_FinalCell3 {
            get {
                object obj = ResourceManager.GetObject("AlwaysEncrypted_NativeColumnEncryptionKeyBaseline_FinalCell3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AlwaysEncrypted_NativeColumnEncryptionKeyBaseline_Plaintext1 {
            get {
                object obj = ResourceManager.GetObject("AlwaysEncrypted_NativeColumnEncryptionKeyBaseline_Plaintext1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AlwaysEncrypted_NativeColumnEncryptionKeyBaseline_Plaintext2 {
            get {
                object obj = ResourceManager.GetObject("AlwaysEncrypted_NativeColumnEncryptionKeyBaseline_Plaintext2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AlwaysEncrypted_NativeColumnEncryptionKeyBaseline_Plaintext3 {
            get {
                object obj = ResourceManager.GetObject("AlwaysEncrypted_NativeColumnEncryptionKeyBaseline_Plaintext3", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
