#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################

name: Recheck Milestones on Version Change

on:
  push:
    branches:
      - main
    paths:
      - src/Microsoft.Data.SqlClient/Versions.props
      - .github/scripts/check-milestone-version.sh
      - .github/scripts/read-sqlclient-version.sh
      - .github/workflows/check-milestone.yml

permissions:
  contents: read
  checks: write
  pull-requests: read

jobs:
  recheck:
    name: Recheck open milestones
    runs-on: ubuntu-latest
    steps:
      - name: Checkout scripts
        uses: actions/checkout@v6
        with:
          # Include the canonical version file used to re-evaluate current PRs.
          sparse-checkout: |
            .github/scripts
            src/Microsoft.Data.SqlClient/Versions.props
          sparse-checkout-cone-mode: false

      - name: Trigger fresh milestone checks
        env:
          BASE_BRANCH: ${{ github.ref_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash "${GITHUB_WORKSPACE}/.github/scripts/recheck-milestones-on-version-change.sh"
