#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################

parameters:
  - name: buildConfiguration
    type: string
    values:
      - Debug
      - Release

  - name: buildSuffix
    type: string

  # Platform Parameters ====================================================

  - name: platformDisplayName
    type: string

  - name: platformDotnet
    type: string

  - name: platformImage
    type: string

  - name: platformOperatingSystem
    type: string

  # Test Configuration Parameters ==========================================

  - name: azureKeyVaultTenantId
    type: string

  - name: azureKeyVaultUrl
    type: string

  - name: connectionStringNp
    type: string

  - name: connectionStringTcp
    type: string

  - name: fileStreamDirectory
    type: string

  - name: localDbAppName
    type: string

  - name: localDbSharedInstanceName
    type: string

  - name: saPassword
    type: string

jobs:
  - job: "test_${{ parameters.platformDisplayName }}_sqlclient_manual"
    displayName: "sqlclient_manual_${{ parameters.platformDisplayName }}"

    pool:
      # TEST
      name: ADO-1ES-Pool
      vmImage: ${{ parameters.platformImage }}

    steps:
      - template: /eng/pipelines/pr/steps/install-dotnet.yml@self
        parameters:
          runtimeVersion: ${{ parameters.platformDotnet }}

      - template: /eng/pipelines/pr/steps/configure-sqlserver-step.yml@self
        parameters:
          fileStreamDirectory: ${{ parameters.fileStreamDirectory }}
          operatingSystem: ${{ parameters.platformOperatingSystem }}
          saPassword: ${{ parameters.saPassword }}

      # @TODO: Document these thingies

      - pwsh: |
          $password = "${{ parameters.saPassword }}"
          Write-Host "##vso[task.setvariable variable=Password;isSecret=true]$password"
        displayName: Set Connection String Password

      - pwsh: |
          try {
              # Read existing default configuration from file
              $defaultConfigPath = "$(REPO_ROOT)/src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/config.default.json"
              $configDirectory = "$(Agent.TempDirectory)/mds-config"
              $configPath = Join-Path $configDirectory "config.json"
              $config = Get-Content -Raw $defaultConfigPath | ConvertFrom-Json

              # Update the config values
              $config.TCPConnectionString = "${{ parameters.connectionStringTcp }}"
              $config.NPConnectionString = "${{ parameters.connectionStringNp }}"
              $config.AzureKeyVaultURL = "${{ parameters.azureKeyVaultUrl }}"
              $config.AzureKeyVaultTenantId = "${{ parameters.azureKeyVaultTenantId }}"
              $config.LocalDbAppName = "${{ parameters.localDbAppName }}"
              $config.LocalDbSharedInstanceName = "${{ parameters.localDbSharedInstanceName }}"
              $config.ManagedIdentitySupported = true
              $config.SupportsIntegratedSecurity = false

              if ("${{ parameters.platformOperatingSystem  }}" -eq "Windows") {
                  $config.FileStreamDirectory = "${{ parameters.fileStreamDirectory }}"
              } else {
                  $config.FileStreamDirectory = ""
              }

              # Write config object to config file
              New-Item -ItemType Directory -Force -Path $configDirectory | Out-Null
              $config | ConvertTo-Json | Set-Content $configPath

              # Set generated config file path to environment variable
              Write-Host "##vso[task.setvariable variable=TEST_MDS_CONFIG]$configPath"
          } catch {
              Write-Host "Generate manual test config failed."
              Write-Host "defaultConfigPath: $defaultConfigPath"
              Write-Host "configDirectory: $configDirectory"
              Write-Host "configPath: $configPath"
              Write-Host "ExceptionType: $($_.Exception.GetType().FullName)"
              Write-Host "ExceptionMessage: $($_.Exception.Message)"
              Write-Host "InvocationInfo:"
              Write-Host $_.InvocationInfo.PositionMessage
              Write-Host "ScriptStackTrace:"
              Write-Host $_.ScriptStackTrace
              Write-Host "ErrorRecord:"
              $_ | Format-List * -Force
              throw
          }
        displayName: 'Generate manual test config'

      - template: /eng/pipelines/pr/steps/test-buildproj-step.yml
        parameters:
          buildConfiguration: ${{ parameters.buildConfiguration }}
          buildSuffix: ${{ parameters.buildSuffix }}

          packageShortName: "SqlClient"
          testFramework: ${{ parameters.platformDotnet }}
          testProject: "Manual"

