#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################

parameters:
  # General Parameters =====================================================

  # Configuration with which to build the packages and execute the tests.
  - name: buildConfiguration
    type: string
    values:
      - Debug
      - Release

  # Suffix to append to the package version to indicate it is a pre-release/development build.
  - name: buildSuffix
    type: string

  # Dotnet CLI verbosity level.
  - name: dotnetVerbosity
    type: string
    default: normal
    values:
      - quiet
      - minimal
      - normal
      - detailed
      - diagnostic

  # Name of the stage that generated the SA password
  - name: stageNameSecrets
    type: string

  # Name of the artifact to upload the test results (including code coverage) to.
  - name: testResultsArtifactBaseName
    type: string

  # Platform Parameters ====================================================

  # Display name of the platform. This will be formatted into the job's official name as well as
  # the display name for the job. As such, only alphanumeric and _ characters are permitted.
  - name: platformDisplayName
    type: string

  # TFM name of the version of dotnet to run this test with.
  - name: platformDotnet
    type: string

  # Name of the image in the customized ADO pool to use to execute this job.
  - name: platformImage
    type: string

  # General name of the operating system that will be used to execute the job.
  # Note: This is used at compile time to determine which SQL Server setup steps to use. As such,
  #    this cannot be replaced with the agent's operating system, as this value is only available
  #    at runtime.
  - name: platformOperatingSystem
    type: string
    values:
      - Windows
      - Linux

  # Name of the pool to use for jobs that require customized VM images.
  - name: poolName
    type: string

  # Test Configuration Parameters ==========================================

  # Azure Key Vault tenant ID that will be set in the config.jsonc file.
  - name: azureKeyVaultTenantId
    type: string

  # Azure Key Vault URL that will be set in the config.jsonc file.
  - name: azureKeyVaultUrl
    type: string

  # Display name for the config being used for this execution of the manual jobs. This will be used
  # for the job name, so it may only contain alphanumeric and '_' characters.
  - name: configDisplayName
    type: string

  # Connection string using named pipes that will be set in the config.jsonc file.
  - name: connectionStringNp
    type: string

  # Connection string using TCP that will be set in the config.jsonc file.
  - name: connectionStringTcp
    type: string

  # Path to use for file stream tests, this value will be stored in the config.jsonc file.
  - name: fileStreamDirectory
    type: string

  # Whether the server that tests will be executed against is local to the job agent. If `true`
  # server configuration steps will be executed prior to running the tests.
  - name: isLocalServer
    type: boolean

  # Whether to enable LocalDB when configuring a local Windows SQL Server.
  - name: enableLocalDB
    type: boolean

  # Name of the local DB application name for localdb tests, this value will be stored in the
  # config.jsonc
  - name: localDbAppName
    type: string

  # Name of the local DB shared instance name for localdb tests, this value will be stored in the
  # config.jsonc
  - name: localDbSharedInstanceName
    type: string

  # Manual test set to execute.
  - name: testSet
    type: string

  # Whether integrated security is supported by this test configuration.
  - name: supportsIntegratedSecurity
    type: boolean

  # Name of the user managed identity client ID. This value will be stored in config.jsonc for use
  # in AKV tests and substituted in for Azure connection string user IDs.
  - name: userManagedIdentityClientId
    type: string

jobs:
  - job: "test_${{ parameters.platformDisplayName }}_${{ parameters.configDisplayName }}_${{ parameters.testSet }}_sqlclient_manual"
    displayName: "sqlclient_manual_${{ parameters.configDisplayName}}_${{ parameters.testSet }}_${{ parameters.platformDisplayName }}"

    pool:
      name: ${{ parameters.poolName }}
      demands:
        - imageOverride -equals ${{ parameters.platformImage }}

    variables:
      # Bring the generated SA password from the secrets stage into scope for this test stage.
      # Note: Because this is set at runtime, it must be referenced as `$(saPassword)`.
      - name: saPassword
        value: $[stageDependencies.${{ parameters.stageNameSecrets }}.secrets_job.outputs['SaPassword.Value']]

      - name: testDisplayName
        value: "sqlclient_manual_${{ parameters.configDisplayName}}_${{ parameters.testSet }}"

      - name: testResultsPath
        value: "$(REPO_ROOT)/test_results/${{ parameters.platformDisplayName }}_$(testDisplayName)"

    steps:
      # Install dotnet and the runtime that will run the tests (if it is not netframework)
      - template: /eng/pipelines/common/steps/install-dotnet.yml@self
        parameters:
          ${{ if not(contains(parameters.platformDotnet, 'net4')) }}:
            runtimes:
              - "${{ replace(parameters.platformDotnet, 'net', '') }}.x"

      # Restore dotnet tools
      - template: /eng/pipelines/common/steps/restore-dotnet-tools.yml@self

      # Configure the local SQL Server instance
      - ${{ if eq(parameters.isLocalServer, true) }}:
        - template: /eng/pipelines/pr/steps/configure-sqlserver-step.yml@self
          parameters:
            enableLocalDB: ${{ parameters.enableLocalDB }}
            fileStreamDirectory: ${{ parameters.fileStreamDirectory }}
            localDbAppName: ${{ parameters.localDbAppName }}
            localDbSharedInstanceName: ${{ parameters.localDbSharedInstanceName }}
            operatingSystem: ${{ parameters.platformOperatingSystem }}
            saPassword: $(saPassword)

      # Assign the generated SA password to the $Password field. This will allow $(Password) to be
      # be replaced in connection strings with whatever set in the secrets stage.
      - pwsh: |
          $password = "$(saPassword)"
          Write-Host "##vso[task.setvariable variable=Password;isSecret=true]$password"
        displayName: Set Connection String Password

      # Write configuration information to the config.jsonc file.
      - pwsh: |
          # Read existing default configuration from file
          $defaultConfigPath = "$(REPO_ROOT)/src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/config.default.jsonc"
          $configDirectory = "$(Agent.TempDirectory)/mds-config"
          $configPath = Join-Path $configDirectory "config.jsonc"
          $config = Get-Content -Raw $defaultConfigPath | ConvertFrom-Json

          # Update the config values
          $config.TCPConnectionString = "${{ parameters.connectionStringTcp }}"
          $config.NPConnectionString = "${{ parameters.connectionStringNp }}"
          $config.AzureKeyVaultURL = "${{ parameters.azureKeyVaultUrl }}"
          $config.AzureKeyVaultTenantId = "${{ parameters.azureKeyVaultTenantId }}"
          $config.LocalDbAppName = "${{ parameters.localDbAppName }}"
          $config.LocalDbSharedInstanceName = "${{ parameters.localDbSharedInstanceName }}"
          $config.ManagedIdentitySupported = $true
          $config.SupportsIntegratedSecurity = [System.Convert]::ToBoolean("${{ parameters.supportsIntegratedSecurity }}")
          $config.UserManagedIdentityClientId = "${{ parameters.userManagedIdentityClientId }}"

          if ("${{ parameters.platformOperatingSystem  }}" -eq "Windows") {
              $config.FileStreamDirectory = "${{ parameters.fileStreamDirectory }}"
          } else {
              $config.FileStreamDirectory = ""
          }

          # Write config object to config file
          New-Item -ItemType Directory -Force -Path $configDirectory | Out-Null
          $config | ConvertTo-Json | Set-Content $configPath

          # Set generated config file path to environment variable
          Write-Host "##vso[task.setvariable variable=TEST_MDS_CONFIG]$configPath"
        displayName: 'Generate manual test config'

      # Execute TestSqlClientManual target from build.proj
      - task: DotNetCoreCLI@2
        displayName: 'Test: SqlClientManual ${{ parameters.testSet }}'
        inputs:
          command: build
          projects: build.proj
          verbosity: ${{ parameters.dotnetVerbosity }}
          arguments: >-
            -t:TestSqlClientManual
            -p:Configuration=${{ parameters.buildConfiguration }}
            -p:BuildNumber='$(Build.BuildNumber)'
            -p:BuildSuffix='${{ parameters.buildSuffix }}'
            -p:TestFramework=${{ parameters.platformDotnet }}
            -p:TestSet=${{ parameters.testSet }}
            -p:TestResultsFolderPath=${{ variables.testResultsPath }}

      # Publish test results
      - template: /eng/pipelines/pr/steps/publish-test-results-step.yml@self
        parameters:
          buildConfiguration: ${{ parameters.buildConfiguration }}
          platformDisplayName: ${{ parameters.platformDisplayName }}
          testDisplayName: ${{ variables.testDisplayName }}
          testResultsArtifactBaseName: ${{ parameters.testResultsArtifactBaseName }}
          testResultsPath: ${{ variables.testResultsPath }}
