#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################

parameters:
  - name: buildConfiguration
    type: string
    values:
      - Debug
      - Release

  - name: buildSuffix
    type: string

  # Platform Parameters ====================================================

  - name: platformDisplayName
    type: string

  - name: platformDotnet
    type: string

  - name: platformImage
    type: string

  # Test Configuration Parameters ==========================================

  - name: azureKeyVaultTenantId
    type: string

  - name: azureKeyVaultUrl
    type: string

  - name: connectionStringNp
    type: string

  - name: connectionStringTcp
    type: string

jobs:
  - job: "test_${{ parameters.platformDisplayName }}_sqlclient_manual"
    displayName: "sqlclient_manual_${{ parameters.platformDisplayName }}"

    pool:
      vmImage: ${{ parameters.platformImage }}

    steps:
      - template: /eng/pipelines/pr/steps/install-dotnet.yml@self
        parameters:
          runtimeVersion: ${{ parameters.platformDotnet }}

      - # @TODO: Config genration step will go here.

      - template: /eng/pipelines/pr/steps/test-buildproj-step.yml
        parameters:
          buildConfiguration: ${{ parameters.buildConfiguration }}
          buildSuffix: ${{ parameters.buildSuffix }}

          packageShortName: ${{ parameters.packageShortName }}
          testFramework: ${{ parameters.platformDotnet }}
          testProject: ${{ parameters.testProject }}

